/**
 * Le mur de la communauté : ce que les membres écrivent dans le groupe Circle.
 *
 * **Rien n'est écrit ici, tout est recopié.** Les `paragraphes` sont le post
 * entier, tel que l'API Circle le rend, découpé en paragraphes et rien de plus.
 * Pas un mot ajouté, pas une phrase reformulée, pas une coquille corrigée :
 * « je n'aurai pas conçu » de Guy est son texte, et c'est comme ça qu'il se
 * publie. C'est la règle des transcriptions d'entretien, et pour la même
 * raison : ce sont les mots de vraies personnes.
 *
 * **Le post entier et non un extrait**, sur demande de Rémy. Un extrait oblige
 * à choisir la phrase qui vend le mieux, ce qui est une façon d'écrire à la
 * place de quelqu'un sans en avoir l'air.
 *
 * **Les trente-neuf posts sortent d'un parcours des 3 768 posts de la communauté**,
 * pas d'une sélection à l'œil. Les rediffusions et les posts de l'équipe ont
 * été écartés, les 492 récits de membres notés sur l'engagement, les marqueurs
 * de récit et de gratitude, puis les meilleurs relus un par un.
 *
 * **Aucun ne donne le prix de nos offres.** C'était la consigne de Rémy. Les
 * montants qui restent sont ceux que les membres gagnent, jamais ce qu'ils ont
 * payé.
 *
 * **Pas de lien vers le post d'origine**, sur demande de Rémy : le groupe est
 * privé, donc le lien mènerait un visiteur non membre à une page de connexion
 * Circle, c'est-à-dire hors du tunnel et dans une impasse. C'est vérifié, pas
 * supposé : un clic de test a bien atterri sur `login.circle.so`.
 *
 * **Ni étoiles, ni compte de réactions.** La carte relevée chez TrendTrack
 * porte cinq étoiles ; personne ici n'a noté Funnels Club, ce sont des posts de
 * communauté et pas des avis notés, et en afficher serait faire dire à
 * quelqu'un ce qu'il n'a pas dit. Les réactions du post avaient pris cette
 * place, parce qu'elles étaient vraies ; Rémy les a retirées, un nombre de
 * cœurs n'apprenant rien à qui découvre la page.
 *
 * **Le `titre` est un extrait, pas un résumé.** C'est une phrase du post,
 * recopiée mot pour mot et vérifiée contre la source, choisie pour donner envie
 * de lire le reste. Écrire un titre par-dessus le texte de quelqu'un reviendrait
 * à lui prêter une intention.
 *
 * **La `niche` vient du profil Circle de la personne**, son `headline`, et de
 * nulle part ailleurs. Trois membres n'en ont pas renseigné : leur carte
 * n'affiche rien sous leur nom. Deviner « coach » ou « formateur » à la lecture
 * de leur post serait leur inventer un métier. Un `headline` qui ne fait que
 * recopier le nom de la personne est écarté au passage : il n'apprend rien.
 *
 * **Les portraits sont ceux de Circle**, servis par nous : une page qui charge
 * ses avatars sur `app.circle.so` fait payer à chaque visiteur une résolution
 * DNS de plus, et ces adresses sont des redirections signées qui expirent.
 *
 * **L'ordre va du résultat le plus exceptionnel au simple mot de gratitude**,
 * sur décision de Rémy, et c'est lui qui décide de ce qu'on voit avant de
 * déplier : François ouvre, Patricia suit. Une même personne peut revenir
 * plusieurs fois, ce que Rémy a demandé explicitement.
 *
 * **`surligne` porte une émotion et un chiffre**, sur sa demande : un montant
 * seul se lit comme une publicité, une émotion seule ne prouve rien. Les deux
 * sont choisis dans le texte, jamais écrits : la phrase la plus courte qui
 * porte un montant, la phrase la plus courte qui porte un sentiment. Un post
 * qui n'a ni l'un ni l'autre n'a pas de surlignage plutôt qu'un surlignage
 * forcé.
 *
 * **`surligne` ne change pas le texte, il le désigne.** Chaque entrée est une
 * sous-chaîne exacte du post, vérifiée par comparaison contre la source, et le
 * rendu ne fait que l'envelopper dans un `mark`. C'est la seule façon de
 * surligner sans réécrire : un passage « mis en avant » qu'on aurait reformulé
 * pour qu'il tienne sur une ligne serait un passage inventé.
 *
 * **Les réponses viennent de l'API, une requête par post.** La v1 de Circle
 * **ignore la pagination** sur ses commentaires : elle rend les cinq cents
 * mêmes à chaque page, ce qui donnait trente mille lignes pour cent
 * cinquante-quatre posts distincts. Le filtre `post_id`, lui, marche. Les
 * réponses de plus de sept cents caractères sont écartées : ce sont des
 * échanges techniques avec un coach, pas des encouragements.
 *
 * **Les noms de famille cités dans les textes ne sont pas retirés d'ici**, mais
 * à l'affichage, par `lib/anonymat.ts`, avec les adresses. Une donnée déjà
 * caviardée ne se vérifie plus contre sa source.
 *
 * **À valider par Rémy, personne par personne.** Ces dix-neuf-là n'ont pas donné
 * leur accord pour figurer sur une page publique : ils ont écrit dans un groupe
 * privé. Un post de communauté n'est pas un témoignage cédé.
 */
export const murCommunaute: readonly {
  nom: string;
  /** Le métier, lu dans le `headline` du profil Circle. `null` s'il est vide. */
  niche: string | null;
  /** `null` quand Circle ne sert pas de portrait : la carte porte l'initiale. */
  portrait: string | null;
  /** Une phrase du post, mot pour mot, qui sert de titre à la carte. */
  titre: string;
  /** Les passages à surligner : une émotion, un chiffre. Sous-chaînes exactes. */
  surligne: readonly string[];
  /** Le post entier, paragraphe par paragraphe, mot pour mot. */
  paragraphes: readonly string[];
}[] = [
  {
    nom: "François Daoud",
    niche: "Professeur de guitare",
    portrait: "/immersion/communaute/francois-daoud.jpg",
    titre: "les choses ont complètement explosé cette semaine",
    surligne: ["Pourtant 24 appels.", "et c’est dingue."],
    paragraphes: [
      "Bonjour à tous,",
      "Aujourd’hui j’avais envie de vous partager mes aventures depuis quelques mois.",
      "Après un été assez calme et un petit moment de stress cet été, les choses ont complètement explosé cette semaine … et c’est dingue.",
      "Bref, je vous raconte !",
      "Pour recontextualiser l’histoire :",
      "J’ai rejoint le Funnels Club en Avril,",
      "En mai, je lance mon offre premium,",
      "Mon offre est une formation impro guitare semi-professionnalisante.",
      "Déjà au début quand je suis arrivé, quand Rémy m’a parlé de proposer une offre à 2000€ minimum, j’étais un peu décontenancé. Même dans mon école de musique physique où la prestation était assez étoffée je ne proposais pas un tel tarif (plutôt autour de 900€).",
      "Finalement, je me suis exécuté, et j’ai appliqué les conseils du coach.",
      "Dès ce mois de mai, sur 10~15 appels, j’en signe 4.",
      "J’ai trouvé ça dingue, d’autant plus que je facture 2000~2500€ la prestation…",
      "Serait-ce la chance du débutant ?",
      "Ayant une chaine Youtube active depuis 2 ans, je me disais qu’il s’agissait peut-être que des prospects très chauds… Et que ça va se dégonfler…",
      "Le mois de Juin a été moins convaincant, je n’ai signé que 2 personnes sur 22 appels.",
      "Ca reste toutefois ~4ke. Donc c’est chouette, mais il y avait ce petit goût de “zut ! Ca n’a pas fonctionné comme j’espérais, ça s’essouffle déjà!”",
      "Et là, arrivent les mois de Juillet et Aout.",
      "Ce sont 2 mois assez difficiles.",
      "1 signature en Juillet, 1 autre en Aout… et c’est tout. Pourtant 24 appels.",
      "Vers la mi-août, suite à un événement un peu compliqué émotionnellement, j’ai commencé à stresser…",
      "Et mon taux de closing était assez bas…",
      "J’ai expliqué mon point à Geoffrey et Rémy, avec cette envie de casser mes prix pour closer davantage.",
      "Pourquoi casser les prix ?",
      "Parce que je voyais bien que c’était constamment à cette étape là que ça coinçait lors des closings.",
      "Donc, à ce stade là (~20 août), les chiffres disaient :",
      "13% de closing global,",
      "mais toutefois…  6,7% de closing sur les 8 dernières semaines (je parle des 8 semaines qui précédaient le mois d’Août)",
      "2 signatures entre juillet et ~20 aout",
      "l’envie de casser les prix pour les descendre à 1400€ au lieu de 2000€.",
      "Et alors que j’allais basculer, je me suis quand même dit que j’allais en parler aux coachs. Chose que j’ai faite (quand même …)",
      "Et j’ai bien fait.",
      "Rémy et Geoffrey ont attiré mon attention sur plein de petits points, et m’encourageaient à garder le cap même si c’était dur, de ne pas me laisser happer par les émotions (ces fameuses émotions…).",
      "D’ailleurs, ils ont également attiré mon attention sur la période, et sur la fausseté de mon calcul (je regardais les 8 dernières semaines au lieu de regarder les 3~4 derniers mois).",
      "Bref, j’ai joué le jeu jusqu’au bout en me disant qu’il faut suivre les conseils et stratégies des coachs.",
      "Finalement, moins de 10 jours plus tard, la machine s’emballe !",
      "Les résa d’appels pleuvent, et j’en arrivent à aujourd’hui :",
      "J’ai signé 5 personnes en 7 jours (9100€).",
      "J’ai plein d’appels de programmés,",
      "D’autres R2 arrivent,",
      "Nous ne sommes que le 5 septembre,",
      "Et j’ai l’impression qu’atteindre 12 à 20ke ce mois ne sera qu’une formalité !",
      "Bref, je ne m’emballe pas trop, mais je suis passé de 1 mois de tréso à 4 mois ! Là, comme ça, en 1 semaine … C’est juste dingue 🙏🙏🙏",
      "Ca y est, la machine s'emble s’emballer 🚀",
      "Moralité de l’histoire : Les coachs ont toujours raison + il faut garder le cap parce que quand ça s’emballe, ça s’emballe !",
      "Edit à j+2 : +4000€ ! Ce qui amène ce mois de septembre à 13100€… et nous ne sommes que le 06/09. C’est juste dingue ce qui se passe…",
    ],
  },
  {
    nom: "Patricia Nagant",
    niche: "Coach Thérapeutique et Holistique  -  \"Accoucheuse d'âme\"",
    portrait: "/immersion/communaute/patricia-nagant.jpg",
    titre: "je vis une aventure absolument magnifique",
    surligne: ["Depuis le 25 juillet, jour où j’ai lancé mon tunnel de vente, je vis une aventure absolument magnifique et je suis remplie de gratitude !"],
    paragraphes: [
      "Depuis le 25 juillet, jour où j’ai lancé mon tunnel de vente, je vis une aventure absolument magnifique et je suis remplie de gratitude ! En seulement quelques jours, j’ai eu la joie de recevoir 11 appels, et j’ai concrétisé 3 ventes en froid et 3 ventes en chaud, pour un total de 20400 €  ! 🙏✨",
      "Je suis tellement reconnaissante pour cette énergie qui circule, pour chaque personne qui a fait confiance à ce projet qui me tient tant à cœur, et pour tout ce que l’univers met en place pour soutenir « Être Aligné ». Je suis vraiment, vraiment fière de ce chemin parcouru, et j’ai hâte de voir tout ce qui continue à se déployer avec autant d’alignement et d’abondance !",
      "PS : Geoffrey, je pense que tu m’as oublié 😊 Peux-tu m’envoyer les deux vidéos promises suite à notre call ?",
      "@Geoffrey Bonniot @Rémy Jupille @Ludivine",
    ],
  },
  {
    nom: "Guy Anastaze",
    niche: "Mentor de dirigeants",
    portrait: "/immersion/communaute/guy-anastaze.jpg",
    titre: "un mandat de 125´000 €",
    surligne: ["Résultat : un mandat de 125´000 € avec un acompte de 37’500 € payable maintenant.", "Je suis infiniment reconnaissant à Rémy et à vous tous pour tout ce que vous m’apportez."],
    paragraphes: [
      "Bonjour à toutes et à tous,",
      "J’ai l’immense plaisir de vous informer qu’un de mes clients a beaucoup aimé le programme de ma formation en ligne que je lui ai présentée, et que je construis grâce à Funnels Club depuis plus d’un an. Il m’a demandé de m’en inspirer pour faire une formation en présentiel pour ses 6 membres du Codir et 6 membres des N—1. (10 jours répartis sur février, mars, avril, juin, septembre 2026).",
      "Résultat : un mandat de 125´000 € avec un acompte de 37’500 € payable maintenant.",
      "Sans Rémy, l’équipe, la communauté et la formation Funnels Club, je n’aurai pas conçu mon offre comme je l’ai faite, et je n’aurais pas eu ce mandat.",
      "Bien que différent de ce que je vise à terme avec ma formation en ligne, cela me montre que des opportunités diverses et fructueuses peuvent surgir grâce à Funnels Club.",
      "Cela me booste pour finir mes modules.",
      "Je suis infiniment reconnaissant à Rémy et à vous tous pour tout ce que vous m’apportez.",
      "Belle journée 🤗",
    ],
  },
  {
    nom: "Judith Kamdem Simo",
    niche: null,
    portrait: null,
    titre: "Je ne savais pas encore que je serais la prochaine à écrire le mien.",
    surligne: ["“Si ça fonctionne à 30 ou 40 %, qu’est-ce qui peut se passer si je m’y mets à 100 % ?”", "Alors merci @Rémy Jupille."],
    paragraphes: [
      "Quand j’ai découvert Funnels Club, je partais vraiment de zéro dans le digital.",
      "J’étais infirmière, je travaillais énormément, toujours des journées de 16 heures, souvent loin de ma famille. Financièrement, je gagnais très bien ma vie — plus de 8 000 $ nets certains mois — mais j’avais l’impression de ne pas avoir de vie. Je voyageais pour travailler, je laissais mes enfants, et au fond de moi je savais que je voulais construire autre chose.",
      "J’étais déjà dans le marketing de réseau, mais je ne savais pas comment vendre mes produits, comment trouver des clients autrement que par la prospection ou le démarchage, ni comment développer réellement mon activité en ligne.",
      "Puis je suis tombée sur une publicité de Rémy.",
      "Je me rappelle encore du déclic. Pendant mon closing, Maxime m’a fait comprendre qu’il était réellement possible de faire venir des clients à soi grâce au digital. Pour moi qui venais du monde traditionnel, ça a complètement changé ma vision.",
      "J’ai payé la formation cash. Je savais que c’était ce que je voulais.",
      "À ce moment-là, je n’avais pourtant pas beaucoup de temps. Quand je travaillais, j’enchaînais mes longues journées. Et pendant mes jours off, je travaillais sur ma formation du matin au soir. Je pouvais m’endormir devant à minuit et me relever à 3 h pour continuer.",
      "Je ratais parfois les coachings en direct, mais je ne ratais pratiquement aucune rediffusion. Je me souviens notamment des heures passées sur la route à écouter les replays de @Maxime LEGROS  sur le closing.",
      "Petit à petit, j’ai commencé à assembler les briques.",
      "J’ai appris à construire mes tunnels.",
      "J’ai appris à lancer mes campagnes publicitaires.",
      "J’ai appris à closer.",
      "J’ai créé mon offre à partir de rien.",
      "Et surtout, j’ai commencé à obtenir mes premiers résultats.",
      "Quand j’ai vu que ça fonctionnait alors que je n’y consacrais encore qu’une partie de mon temps, je me suis posé une question très simple :",
      "“Si ça fonctionne à 30 ou 40 %, qu’est-ce qui peut se passer si je m’y mets à 100 % ?”",
      "C’est là que j’ai pris une décision qui aurait été inimaginable pour moi auparavant : j’ai quitté mon métier et mon gros salaire pour me consacrer entièrement à ce que j’étais en train de construire.",
      "Tout n’a pas été facile. Il y a eu du stress, des périodes de doute, des choses à ajuster. Mais j’avais appris une phrase que je n’ai jamais oubliée :",
      "““Faire plus de ce qui marche et moins de ce qui ne marche pas””.",
      "Mes campagnes fonctionnaient, mais je savais qu’il me manquait encore quelque chose pour passer un cap.",
      "C’est là que @Geoffrey Bonniot  est intervenu.",
      "J’hésitais presque à demander autant d’aide, parce que je savais à quel point son temps était précieux. Mais il a accepté de travailler avec moi.",
      "Et là, les choses ont réellement accéléré.",
      "En seulement quelques mois, je suis passée d’environ 5 000 $ de chiffre à plus de 20 000 $, puis aujourd’hui, en plein mois d’août, je suis proche des 50 000 $.",
      "Et quand je regarde tout ça, ce qui me frappe le plus n’est même pas seulement le chiffre.",
      "C’est de me dire qu’une femme qui ne connaissait rien au digital, qui n’avait jamais construit de business en ligne, qui venait d’un métier totalement traditionnel, arrive aujourd’hui à mettre de la nourriture sur la table de sa famille grâce à ce qu’elle a appris à construire sur Internet.",
      "Je crois que ma plus grande leçon, c’est celle-ci :",
      "j’ai compris que je n’avais plus envie de perdre du temps à essayer de tout comprendre seule.",
      "Je préfère investir pour apprendre auprès de personnes qui ont déjà les résultats que je veux atteindre.",
      "Je paierais cher pour ne pas me tromper.",
      "Funnels Club m’a donné cette structure, cette vision et ces compétences que je n’avais pas.",
      "Alors merci @Rémy Jupille.",
      "Merci @Maxime LEGROS  pour toutes ces heures d’enseignement sur le closing.",
      "Et merci infiniment @Geoffrey Bonniot  pour l’accompagnement qui m’a permis de passer un nouveau cap.",
      "Quand je suis arrivée ici, je lisais les témoignages des autres en me demandant si un jour ce serait mon tour.",
      "Je ne savais pas encore que je serais la prochaine à écrire le mien.",
    ],
  },
  {
    nom: "Laëtitia Miroux",
    niche: "Fondatrice Exportateurs Engagés - Méthode structurée, résultats export concrets",
    portrait: "/immersion/communaute/laetitia-miroux.jpg",
    titre: "une mission à 15 000 dollars",
    surligne: ["Début juillet, j'ai signé mon premier membre au nouveau tarif grâce au processus de closing (2500 euro - tarif qui évoluera encore).", "Je suis vraiment heureuse, parce que ça confirme plusieurs choses."],
    paragraphes: [
      "@Geoffrey Bonniot @Rémy Jupille @Ludivine",
      "J'avais envie de partager une petite victoire avec vous.",
      "J'ai lancé une version non finie des Exportateurs Engagés en janvier. J'ai eu mes premiers membres à partir de fin mars à un tarif imbattable. Ils étaient trois. Ensuite, j'ai volontairement ralenti pour construire les fondations : travailler ma publicité, mon tunnel de vente et appliquer la méthode de Funnels Club étape par étape.",
      "Début juillet, j'ai signé mon premier membre au nouveau tarif grâce au processus de closing (2500 euro - tarif qui évoluera encore).",
      "Et aujourd'hui, une nouvelle étape vient d'être franchie.",
      "J'ai présenté ma méthode à un distributeur de produits canadiens qui souhaite se développer au Brésil. Au départ, je pensais lui vendre le programme. Finalement, il m'a expliqué qu'il ne souhaitait pas former quelqu'un en interne, mais qu'il voulait que j'applique directement ma méthode pour son entreprise.",
      "Résultat : nous sommes partis sur une mission à 15 000 dollars (hors commission) pour mettre en place la méthode Exportateurs Engagés sur le marché brésilien.",
      "Je suis vraiment heureuse, parce que ça confirme plusieurs choses.",
      "D'abord, avoir fait confiance à ma méthode et avoir suivi les conseils de Funnels Club m'a permis de construire une offre qui répond à un vrai besoin.",
      "Ensuite, ce projet va me permettre d'obtenir un cas concret, récent et très solide. Je suis convaincue qu'il deviendra un excellent support de communication pour faire rayonner Exportateurs Engagés.",
      "En parallèle, mon nouveau membre avance bien dans le programme, et grâce à la publicité, je reçois de plus en plus d'appels. Je sens que la machine est en train de se mettre en route.",
      "Les résultats ne sont pas arrivés du jour au lendemain. Ils se sont construits progressivement, avec des confirmations qui sont tombées sur plusieurs semaines. Mais aujourd'hui, je vois que le travail de fond finit par payer.",
      "Merci beaucoup à @Geoffrey Bonniot et à toute la communauté pour les conseils et les échanges. Ça motive à continuer.",
    ],
  },
  {
    nom: "François Daoud",
    niche: "Professeur de guitare",
    portrait: "/immersion/communaute/francois-daoud.jpg",
    titre: "j’ai fait une nouvelle vente !",
    surligne: ["Trop content : +2k€ !", "A voir si ça signe, mais si oui, je vous tiens au courant, et ce serait absolument ENORME."],
    paragraphes: [
      "Hello à tous !",
      "Je vous partage ma nouvelle réussite ! Lundi dernier, quelques heures avant de prendre l’avion pour une petite semaine de coupure en amoureux, j’ai fait une nouvelle vente !",
      "Trop content : +2k€ ! Ce qui m’amène à 12ke depuis mon arrivée au Funnels Club (début avril). Ce n’est que le début, et je sens que les choses commencent doucement à s’accélérer !",
      "Grande nouveauté :",
      "Hier, j’ai eu 4 appels, 2 sont très intéressés et à suivre pour le R2.",
      "Mais la nouveauté, c’est que j’ai fait évoluer mon tarif :",
      "Jusqu’à maintenant, j’étais à 2000€ pour la formation de 10 mois",
      "Je suis passé à 2500€ pour une durée de 8 mois !",
      "A voir si ça signe, mais si oui, je vous tiens au courant, et ce serait absolument ENORME.",
      "A suivre !",
    ],
  },
  {
    nom: "Many Soliman",
    niche: null,
    portrait: "/immersion/communaute/many-soliman.jpg",
    titre: "j’ai réalisé mes 2 premiers closings pour ma bêta",
    surligne: ["Pour le moment, j’ai reçu de chaque côté un acompte de 250 €, le temps qu’ils s’organisent financièrement :", "en tout cas je suis hyper content."],
    paragraphes: [
      "🔥 Petite update du jour !",
      "Aujourd’hui, j’ai réalisé mes 2 premiers closings pour ma bêta :  un premier à 1000 € et  un second à 1500 €",
      "Deux personnes super motivées et totalement partantes pour démarrer la formation avec moi dès lundi.",
      "Pour le moment, j’ai reçu de chaque côté un acompte de 250 €, le temps qu’ils s’organisent financièrement :",
      "paiement en 2 fois pour l’un Et un paiement en 3 fois pour l’autre.",
      "Petite info aussi : le dernier prospect lors de la panne m’a finalement ghosté, plus de nouvelles depuis.",
      "en tout cas je suis hyper content. Ces deux ventes sont le fruit de beaucoup de travail. Je sais que j’ai encore beaucoup à apprendre mais c’est un premier checkpoint important pour mon projet.",
      "Un merci particulier pour @Geoffrey Bonniot et @Kylian Baude qui on été jusque la ,mes interlocuteurs.",
    ],
  },
  {
    nom: "Guy Anastaze",
    niche: "Mentor de dirigeants",
    portrait: "/immersion/communaute/guy-anastaze.jpg",
    titre: "Je viens de réaliser mon premier closing avec un bêta-testeur !",
    surligne: ["Décision prise : il me verse immédiatement 500 CHF d’acompte sur les 2’000 CHF de l’offre bêta-testeur — mon offre complète étant à 6’000 CHF.", "Et là, excellente surprise : son épouse est très soutenante."],
    paragraphes: [
      "Bonjour à toutes et à tous,",
      "🎉 Je viens de réaliser mon premier closing avec un bêta-testeur ! Je voulais partager avec vous le contexte et surtout les enseignements que j’en retiens.",
      "J’ai lancé mes publicités Facebook il y a deux mois. Résultat à ce jour : trois prises de rendez-vous, dont un no-show.",
      "Lors du R1, le prospect est clairement qualifié. Lorsqu’il me dit qu’il devra en parler à son épouse, je l’invite à participer au R2.",
      "Et là, excellente surprise : son épouse est très soutenante. Elle a elle-même suivi un programme sur l’hypnose avec un tunnel de vente similaire au nôtre — donc confiance dans l’approche — et elle est en train de lire mon livre sur la vente — donc confiance en moi.",
      "Au moment de décider, mon prospect est partant, mais souhaite d’abord solliciter sa DRH pour une éventuelle participation de son entreprise.",
      "Je lui demande alors : « Et si elle refuse, que se passe-t-il ? »",
      "Son épouse lui donne une petite pichenette et lui dit en substance : « Prends ta décision maintenant. C’est un investissement pour ton avenir. »",
      "Décision prise : il me verse immédiatement 500 CHF d’acompte sur les 2’000 CHF de l’offre bêta-testeur — mon offre complète étant à 6’000 CHF. 😊",
      "Un grand merci à Rémy pour ses précieux conseils lors de nos coachings hebdomadaires. Deux ont fait toute la différence ici :",
      "Faire venir le codécisionnaire.",
      "Poser la question du pire scénario : « Et dans le pire des cas, que se passe-t-il ? »",
      "Deux conseils simples… et très concrets ! 🙏",
    ],
  },
  {
    nom: "Jeremy Renoux",
    niche: null,
    portrait: "/immersion/communaute/jeremy-renoux.jpg",
    titre: "mon premier close en 1X à 1800€",
    surligne: ["Victoire qui fait du bien mon premier close en 1X à 1800€.", "Je suis plutôt content :D."],
    paragraphes: [
      "Hello à toutes et tous ^^",
      "J’espère que vous allez bien et que vos tunnels se portent au mieux.",
      "Victoire qui fait du bien mon premier close en 1X à 1800€. Je suis plutôt content :D.  Alors petite dédicace à toi @Rémy Jupille et toi aussi @Geoffrey Bonniot . Il me parait loin le temps ou j’avais cette appréhension au téléphone avant d’appeler mes prospects….",
      "@Geoffrey Bonniot je t’ai fait une video en mp. Scaling or not scaling … that is the question ?",
      "Une excellente semaine à tous les funneliens et funneliennes",
      "Best",
      "Jerem",
    ],
  },
  {
    nom: "Lilian Céré",
    niche: "Dirigeant d’une agence web spécialisé dans le BTP",
    portrait: "/immersion/communaute/lilian-cere.jpg",
    titre: "Je fais ce post pour ceux qui doutent.",
    surligne: ["Je fais ce post pour ceux qui doutent."],
    paragraphes: [
      "Je fais ce post pour ceux qui doutent.",
      "Cette semaine, j’ai closé deux clients. Et si je le partage, ce n’est pas pour me la raconter, mais pour être honnête sur le chemin.",
      "Ça fait longtemps que je travaille le closing. Et clairement, j’y ai pris quelques leçons de vie.",
      "Il y a deux semaines, j’avais un client hyper intéressant. Engagement en visio, échange fluide, tout était validé. Il ne manquait plus qu’une chose : qu’il rentre sa carte.",
      "On a repoussé le paiement à plus tard dans la journée. On n’était plus en visio. Et finalement… il n’a jamais payé.",
      "Sur le moment, j’ai même hésité à poster dans le groupe pour dire que j’avais signé. Et puis je me suis dit : attends qu’il paye. J’ai bien fait. Parce que ce client-là n’a jamais signé.",
      "Et ça m’a rappelé une chose essentielle : le closing, ce n’est pas facile.",
      "Mais quand le travail est fait sérieusement, quand on se fait accompagner, quand on analyse, qu’on corrige et qu’on continue… les choses finissent par s’aligner.",
      "Cette semaine, grâce au travail effectué et à l’accompagnement de Rémy et de toute l’équipe de Funnel Club, j’ai réussi à en signer deux.",
      "Ce que j’en retiens : le closing, ce n’est pas un talent. Ce n’est pas instantané. Et ce n’est clairement pas ce qu’on voit sur les réseaux.",
      "C’est de la progression, de l’entraînement, du volume. Faire des calls. Les réécouter. Analyser ceux qui n’ont pas marché… mais aussi ceux qui ont marché, pour se demander : comment j’aurais pu faire encore mieux ?",
      "C’est juste une question de temps.",
      "Aujourd’hui, je voulais surtout remercier toute l’équipe de Funnel Club ! Parce que je suis encore au début. Et justement… ce n’est que le début. Je compte bien continuer à progresser et tout arracher 🚀",
      "Et pour ceux qui doutent en ce moment, ou qui ont l’impression de stagner : ne perdez pas espoir. Le closing n’est pas une question de chance ni de talent inné. C’est une question de temps, de répétition et d’amélioration continue.",
      "Continuez à faire des calls. Continuez à les analyser. Continuez à progresser.",
      "Le reste finit toujours par suivre.",
    ],
  },
  {
    nom: "Alexandre Vandame",
    niche: null,
    portrait: "/immersion/communaute/alexandre-vandame.jpg",
    titre: "Maintenant que tout est bien en place, je reviens pour faire décoller l'ensemble pour de bon.",
    surligne: ["- 31 réservations d'appel avec 40% noshow, 44% des présents poussés en stratégie, et 1 vente à 1050€.", "Merci pour ton aide"],
    paragraphes: [
      "Bonjour @Geoffrey Bonniot ,",
      "Retour après quelques mois de silence apparent!",
      "Maintenant que tout est bien en place, je reviens pour faire décoller l'ensemble pour de bon.",
      "Voici la situation à ce jour :",
      "- Tunnel complètemment finalisé",
      "- Campagnes de pub relancées depuis cet été",
      "- une base de 1000+ emails, mais j'ai du mal à en estimer la qualité...",
      "- 31 réservations d'appel avec 40% noshow, 44% des présents poussés en stratégie, et 1 vente à 1050€. Je commence à prendre mes marques avec le closing et avoir une vente permet d'aller jusqu'au bout du process (signature contrat, intégration etc...)",
      "- création de contenu en cours, un peu tard mais c'est lancé (insta/fb).",
      "Sur les dernières semaines :",
      "- j'ai pas mal modifié mes pub et la structuration des campagnes après avoir constaté que les coûts s'envolaient depuis un moment (CPC = 1,80€ et CPL à 25€ env).",
      "- le cout par prospect redescend (CPL à 10-12€), mais je n'ai plus de réservation d'appel depuis une 15ne de jours...",
      "- un pb technique : j'ai rajouté de nouvelles pubs dans un adset, mais elles ne sont visiblement même pas testées. Faut-il créer un nouvel adset à chaque fois qu'on lance de nouvelles pub ?",
      "Idéalement, j'aurais besoin d'un avis global sur la situation pour savoir dans quelle direction avancer : tunnel, webinar, pub...",
      "Je te joins un lien vers les captures d'écran et mes tableaux de suivi.",
      "https://drive.google.com/drive/folders/1WP2jS_XKfjaRN_YNDLYUhfRkz2Y7jrob?usp=sharing",
      "Dis-moi si tu as besoin de plus d'éléments, notamment sur les pub ou revue du webinar...",
      "Merci pour ton aide",
      "Alexandre",
    ],
  },
  {
    nom: "Cédric Bizet",
    niche: "J'aide les entrepreneurs à se digitaliser.",
    portrait: "/immersion/communaute/cedric-bizet.jpg",
    titre: "je partais de rien, 0 connaissance",
    surligne: ["Ravi de découvrir cette nouvelle version après quelques mois d’absence.."],
    paragraphes: [
      "Bonjour à toutes et à tous,",
      "Ravi de découvrir cette nouvelle version après quelques mois d’absence..",
      "Je tiens avant tout à vous remercier vous, la superbe équipe de Rémy, c’est vrai qu’on a tendance à l’oublier et à rester la tête dans notre business, notre projet, égoïstement. Mais il faut le souligné vous êtes comme nos grand frères / nos grandes sœur, toujours là pour nous booster quand on a un coup de mou et surtout là pour nous tirer vers le haut dans les moments compliqués. On peut compter sur vous et tout le monde c’est à quel point c’est important.",
      "J’ai lu ta lettre Rémy, et j’ai directement compris de quoi tu parlais, et j’espère que tout le monde réalise à quel point on est bien tombé ici à Funnels club, vous avez un coeur en or et vous mérité qu’on vous le dise plus souvent, MERCI ! J’espère avec ce message vous effacez un peu de cette frustration qui peut venir par moment.. C’est pas toujours évident même pour vous :)",
      "En tout cas, soyez en sur vous faites de l’excellent boulot, c’est grâce à funnels club que j’ai débuté le business, je partais de rien, 0 connaissance, et maintenant je gagne plusieurs milliers d’euros et vous n’y êtes pas pour rien !",
      "Funnels club évolue et à chaque fois de mieux en mieux, hâte de découvrir ces nouvelles vidéos d’état d’esprit.",
      "Et pour les nouveaux membres sachez que funnels club c’est bien plus qu’une communauté, c’est une famille, certes ça a un coût mais les personnes ici sont toutes prêtes à vous aider et à vous propulser vers la réussite, en tout cas si vous avez des questions ou quoique ce soit je serais ravi de vous aider à mon échelle !",
    ],
  },
  {
    nom: "Séverine Sassard",
    niche: "Coach perte de poids pour les femmes de plus de 40 ans",
    portrait: "/immersion/communaute/severine-sassard.jpg",
    titre: "j’ai réalisé mes 2 premières ventes en offre Bêta",
    surligne: ["Pour moi, c’est énorme."],
    paragraphes: [
      "Bonjour à toute l’équipe,",
      "Je voulais partager une petite (grande !) victoire : j’ai réalisé mes 2 premières ventes en offre Bêta 🎉",
      "Pour moi, c’est énorme. Je lutte beaucoup avec le syndrome de l’imposteur, alors réussir à concrétiser ces premières ventes a une valeur toute particulière.",
      "Un immense merci à toute l’équipe du Funnel Club. C’est la première fois que j’arrive réellement à vendre et je sais que votre accompagnement y est pour beaucoup.",
      "Pour celles et ceux que ça intéresse : – La communication s’est faite via mes réseaux sociaux – Les inscriptions sont passées par le webinar : une vente directement et une autre après le deuxième mail de relance.",
      "Maintenant, je reste dans le mouvement : accompagnement de mes clientes, alimentation de mon espace membre, animation de mes réseaux et préparation de mes publicités avec @Geoffrey Bonniot .",
      "Car après les premières ventes, une nouvelle question arrive : Est-ce que je vais réussir à en refaire, surtout avec un agenda de réservation vide ?",
      "Alors en ce moment, je travaille beaucoup mon mental. Je choisis de rester rationnelle : si je continue les actions, les résultats reviendront. C’est mathématique… Je refuse de laisser le doute prendre le dessus.",
      "Aujourd’hui, je suis fière et heureuse. J’ai hâte de me lancer dans l’aventure des publicités !",
      "Merci encore à vous tous",
    ],
  },
  {
    nom: "Sacha Cohen",
    niche: "Nettoyage Boost System",
    portrait: "/immersion/communaute/sacha-cohen.jpg",
    titre: "4h après mon post j’ai ma première vraie vente",
    surligne: ["enfin pas vraiment, des dépôts de 50€ 😅😅", "Je suis content et frustré en même temps haha…"],
    paragraphes: [
      "Petit post pour donner quelques chiffres. Depuis début août :",
      "17 réservations rien que pour la 1ère semaine du mois (planning full 😬)",
      "j’ai pour le moment fait 2 stratégies",
      "2 ventes… enfin pas vraiment, des dépôts de 50€ 😅😅",
      "Je suis content et frustré en même temps haha…",
      "Je ne sais pas vraiment si les dépôts vont tenir vers la vente finale ou être remboursés mais ça fait plaisir, c’est encourageant.",
      "Après avoir fait des dizaines et dizaines de call sur tout juillet, je sens que je prends les appels (et les objections) autrement, j’ai la sensation de mieux connaître, affiner ce que j’ai dis (ce qui est normal).",
      "Voilà maintenant je me demande comment ça va se passer pour remplir les 10 places de mes membres fondateurs pour l’offre bêta (sans parler de l’offre finale 🙏🏼) mais en tout cas j’ai l’impression d’avoir débloqué quelque chose de nouveau…",
      "À suivre 🙂",
      "EDIT : 4h après mon post j’ai ma première vraie vente 🥹",
      "Une prospect avec qui j’avais fais 2 RDV en juillet (et qui n’avait à ce moment même pas la possibilité de faire un dépôt de 50€) est revenue vers moi, prête à passer à la suite et qui s’est conclue en première vente avec un paiement en 3 fois 🫣",
    ],
  },
  {
    nom: "Sacha Cohen",
    niche: "Nettoyage Boost System",
    portrait: "/immersion/communaute/sacha-cohen.jpg",
    titre: "j’ai fais une nouvelle vente vendredi",
    surligne: ["Cash à venir sur les prochains mois : 632€ (si tout se passe bien)", "C’est super positif mais j’ai comme l’impression de pas être fier de moi."],
    paragraphes: [
      "Hello,",
      "J’écris ce post pour informer que j’ai fais une nouvelle vente vendredi. 🥳",
      "C’est super positif mais j’ai comme l’impression de pas être fier de moi.",
      "C’est comme si il n’y avait pas vraiment eu d’objections et ça avait été facile.",
      "Il y a en quand même eu, des questions également mais j’ai l’impression que ça s’est passé de manière trop clean 😅",
      "J’ai conscience que c’est super positif, que c’est grâce à la stratégie et mon travail mais je reste très stoïque, presque sans émotions ou sentiments par rapport à ce nouveau client.",
      "Je pense aussi que ce qui joue c’est que la personne a payé via virement en 2 fois. Et je pense me dire inconsciemment que le virement du mois prochain ce sera peut-être à son bon vouloir (malgré le contrat signé) car je suis toujours dans l’offre bêta et donc pas encore de contenu sorti par rapport à ce qu’il a acheté.",
      "Enfin bref, c’est quand même du positif.",
      "Pour le moment, mes résultats en août :",
      "2 ventes. Soit 1 paiement en 2 fois (via virement), un paiement en 3 fois (par CB Stripe)",
      "2 dépôts (incertains, c’est à 2 doigts du remboursement, je bosse dessus)",
      "Cash collecté : 466€ (dont 100€ en dépôt que je vais peut-être devoir rembourser)",
      "Cash à venir sur les prochains mois : 632€ (si tout se passe bien)",
      "J’ai encore 2 stratégies avant la fin du mois, je ferai un edit sur ce post afin de donner mes résultats définitifs de ce mois d’août.",
      "EDIT : un dépôt a été fait en R2 après que j’ai écrit ce post pour que la personne ait le temps de s’organiser financièrement en début de mois 🙂",
    ],
  },
  {
    nom: "Mathieu Granchamp",
    niche: null,
    portrait: "/immersion/communaute/mathieu-granchamp.jpg",
    titre: "j’ai officiellement closé ma première cliente",
    surligne: ["C’était d’ailleurs un jour symbolique pour plusieurs raisons, et notamment parce que ça faisait exactement 10 mois que j’ai commencé ce projet.", "Quelle joie, quel bonheur !"],
    paragraphes: [
      "Nous y voilà, hier soir, j’ai officiellement closé ma première cliente ! Quelle joie, quel bonheur !",
      "C’était d’ailleurs un jour symbolique pour plusieurs raisons, et notamment parce que ça faisait exactement 10 mois que j’ai commencé ce projet.",
      "J’ai commencé à bosser dessus dans l’ombre seul et sans stratégie le 9 février 2025 et moins d’un an plus tard, j’ai débloqué cette fameuse “deuxième source de revenus”. A savoir qu’en tant que kiné et ayant déjà beaucoup de charges, je réalise beaucoup de consultations par semaine (45h/semaine), donc tout mon temps libre est allouée à mes objectifs. (Sachant que je forme tous les mois, donc je n’ai même pas fait que FC)",
      "J’ai rejoint FC le 24 août mais j’avais déjà une bonne base (system.io, mon offre pratiquement bouclée, déjà essayé fb ads), cela m’a donné un coup d’accélérateur : 3 mois et demi plus tard, nous y voilà à la première vente.",
      "Un grand merci à tous les coaches et aux membres :",
      "@Rémy Jupille pour FC et la stratégie",
      "@Geoffrey Bonniot pour le dévouement (je me souviens notamment que tu as répondu à la refonte de mon copywriting à 15h un samedi donc si tu étais à Maurice, 19h ?)",
      "@Maxime LEGROS pour les rediff de coaching que j’écoute attentivement",
      "@François DAOUD qui m’a donné envie de commencer à écouter les rediff de closing quand il en avait partagé une ainsi que son témoignage en septembre",
      "@Nicolas Majois ❤️ @Many Soliman ❤️ @Clemence Privé @Olivier CAETANO @Marlyse et Richard de Villeneuve @Laurent et Élisabeth. pour les encouragements et le soutien !",
      "et finalement @Mattys Hamonic !",
      "IMG_4844.mov",
    ],
  },
  {
    nom: "Nicolas Majois",
    niche: "Arrêter de boire c'est facile 👌",
    portrait: "/immersion/communaute/nicolas-majois.jpg",
    titre: "Voilà c’est fait",
    surligne: ["Ma banque qui bloque facebook en tant que bénéficiaire douteux …"],
    paragraphes: [
      "🎉🎉Voilà c’est fait🎉🎉 La machine est lancée 💪",
      "C’était pas facile, J’ai lancé mes pubs il y a un mois, et au bout de 15 jours elles avaient planté.",
      "Une semaine sans pub avant de dupliquer la campagne et de recommencer la phase d’apprentissage.",
      "Pas les mêmes pubs misent en avant et de moins bons résultats. Ma banque qui bloque facebook en tant que bénéficiaire douteux … indéblocable qu’ils disent … Mais j’me suis pas décourager, que du contraire enfait. Et voilà vendredi un call, aujourd’hui première vente 😄 J’suis trop content haha.",
    ],
  },
  {
    nom: "Colas Zibaut",
    niche: "Spécialiste en Bien-être & Performance Numérique",
    portrait: "/immersion/communaute/colas-zibaut.jpg",
    titre: "j’ai mon premier client",
    surligne: ["Quelle joie de voir enfin la section '“vente” se remplir sur system.io"],
    paragraphes: [
      "Collègues funneliens,",
      "Un petit mot pour vous partager que j’ai mon premier client. Quelle joie de voir enfin la section '“vente” se remplir sur system.io",
      "Bon, c’est un ami donc il avait forcément une confiance très forte, et j’ai mis plus de deux mois à le closer entre le premier et le second appel.",
      "Donc pour dire que la patience paie.",
      "Merci à l’équipe pour le soutien @Geoffrey Bonniot @Rémy Jupille @Maxime LEGROS 🙌🏻 Et merci à vous tous pour l’inspiration",
      "Pour celles et ceux qui ne sont pas encore à ce stade, j’espère que cette nouvelle vous donnera de la motivation 💪🏼",
    ],
  },
  {
    nom: "Mario Orsinet",
    niche: "Musicien/Professeur de musique",
    portrait: "/immersion/communaute/mario-orsinet.jpg",
    titre: "je viens d’encaisser ce matin un premier paiement pour mon offre Bêta",
    surligne: ["C’est un acompte de 100€ pour une offre à 300€.", "C’est pas énorme mais ce n’est que le début 🚀 et c’est très encourageant pour la suite."],
    paragraphes: [
      "Salut à tous!",
      "📢 Je suis très heureux de vous annoncer que je viens d’encaisser ce matin un premier paiement pour mon offre Bêta.😁",
      "C’est un acompte de 100€ pour une offre à 300€. C’est pas énorme mais ce n’est que le début 🚀 et c’est très encourageant pour la suite.",
      "J’en profite pour dire un GRAND MERCI 🙏🙏🙏 à @Rémy Jupille @Geoffrey Bonniot et à tous les coachs pour les conseils et le soutien.",
      "Je continue d’avancer et courage 💪 à ceux qui démarre avec Funnel Club. Les efforts investis finissent toujours par payer !!!",
    ],
  },
  {
    nom: "Laëtitia Miroux",
    niche: "Fondatrice Exportateurs Engagés - Méthode structurée, résultats export concrets",
    portrait: "/immersion/communaute/laetitia-miroux.jpg",
    titre: "je vous partage mes récents résultats - j’en suis assez fière",
    surligne: ["Ce qui fait un taux de conversion en rendez-vous de plus de 21% (4/19=21%) - je suis contente de ces résultats.", "Merci et à bientôt,"],
    paragraphes: [
      "Bonjour @Geoffrey Bonniot / @Rémy Jupille / tout le monde",
      "Belle année 2026 - je vous souhaite de la concrétisation dans vos projets respectifs !",
      "En ce début d’année, je vous partage mes récents résultats - j’en suis assez fière et j’espère que ce n’est qu’un commencement !",
      "Avant de partir en vacances le 18 décembre dernier, j’ai envoyé 19 emails à mes contacts pour présenter mon programme Exportateurs Engagés et pour déclarer ma recherche de testeurs.",
      "Entre ce 18 décembre et aujourd’hui, ces 19 emails ont généré :",
      "6 contacts ont été engagés et",
      "4 rendez-vous ont été positionnés la semaine prochaine pour commencer le recrutement de mes premiers bêta testeurs",
      "un 5 ème rdv est en route (la confirmation devrait arriver cette semaine)",
      "Ce qui fait un taux de conversion en rendez-vous de plus de 21% (4/19=21%) - je suis contente de ces résultats. Pour vous - les coachs - est-ce pas mal ou peu mieux faire 😉?",
      "Cette semaine, je regarde les vidéos sur le closing pour me préparer à utiliser cette méthode que je trouve très pertinente ! Et j’ai hâte de l’utiliser !",
      "Merci et à bientôt,",
      "Laëtitia",
    ],
  },
  {
    nom: "Barbara Bay",
    niche: "Je forme les professionnels de l'accompagnement a intégrer leurs perceptions extra-sensorielles en séance",
    portrait: "/immersion/communaute/barbara-bay.jpg",
    titre: "j’ai eu une jolie surprise hier",
    surligne: ["Alors, j’ai eu une jolie surprise hier."],
    paragraphes: [
      "Bonjour à tous, bonjour l’équipe. J’avance pas à pas sur la personnalisation du tunnel et j’en vois doucement le bout. Grâce au module mindset, aux coachs et à la super communauté, je garde le cap mais je dois dire que ce travail de l’ombre est long et les peurs embusquées à chaque intersection.",
      "Alors, j’ai eu une jolie surprise hier.",
      "Comme j’ai déjà quelques centaines de personnes abonnées à ma newsletter, j’ai déjà évoqué mon projet de formation et il y en a une ébauche sur mon site internet.",
      "Grâce à cela, j’ai eu la bonne surprise de trouver hier un rendez-vous dans mon calendly d’une personne qui m’explique spontanément, en détail, ce qu’elle recherche, et on dirait qu’elle a déjà suivi tout le processus de qualification.",
      "Elle correspond à mon prospect de rêve ! C’est un très bon signe. Elle a même eu l’élégance de prendre son rendez-vous pour dans 4 jours, ce qui me laisse le temps d’aller voir les vidéos sur les appels de qualification et de closing ! 😄",
      "Voilà ma première victoire :-)",
    ],
  },
  {
    nom: "Tatiana Moreau",
    niche: "Coach Holistique",
    portrait: "/immersion/communaute/tatiana-moreau.jpg",
    titre: "j'avais pour objectif d'atteindre les 1000 abonnés sur YT en 6 mois",
    surligne: ["C'est un mini objectif atteint début octobre qui permet de générer des leads 😊 même si 1000 abos paraît peu dit comme ça, j'en suis contente !"],
    paragraphes: [
      "Petit partage de mini-victoire : j'avais pour objectif d'atteindre les 1000 abonnés sur YT en 6 mois et lancé ma chaîne en avril 2025 en postant 1 vidéo YT par semaine (pas de YT Shorts).",
      "C'est un mini objectif atteint début octobre qui permet de générer des leads 😊 même si 1000 abos paraît peu dit comme ça, j'en suis contente ! Voilà c'est tout !!",
    ],
  },
  {
    nom: "Karine Köhli",
    niche: "Coach StopBurnOut",
    portrait: "/immersion/communaute/karine-kohli.jpg",
    titre: "Je voulais partager deux victoires avec vous.",
    surligne: ["Budget max par jour, 5 CHF.", "Merci à Geoffrey pour son aide."],
    paragraphes: [
      "Bonjour,",
      "Je voulais partager deux victoires avec vous. J’ai mis en ligne mes pubs sur meta samedi après-midi et ça c’est déjà une victoire incroyable pour moi, car j’ai eu beaucoup de problèmes techniques. Merci à Geoffrey pour son aide. Budget max par jour, 5 CHF.",
      "Aujourd’hui, je vois que deux personnes ont donné leur adresse mail pour visionner le webinar. Je ne suis pas sûre s’ils ont regardé et d’ailleurs je ne suis pas sûre de savoir comment vérifier cela, mais je suis déjà hyper contente qu’après même pas 48 heures j’ai deux adresses mails.",
      "Voilà, pour mes petites victoires 😊",
    ],
  },
  {
    nom: "Corentin Ghisalberti",
    niche: null,
    portrait: "/immersion/communaute/corentin-ghisalberti.jpg",
    titre: "ce n’est pas un sprint, c’est un marathon",
    surligne: ["J’aurai la chance de passer 4 mois en Asie, entre Bangkok et Kuala Lumpur, avant d’arriver à Abu Dhabi le 13 mars.", "🙏 Merci pour tout."],
    paragraphes: [
      "Salut à tous !",
      "J’espère que vous allez bien 😊",
      "Aujourd’hui, certains de mes clients m’ont remercié pour le travail que je faisais et pour tout ce que j’apportais à leur entreprise au quotidien et ça m’a vraiment fait chaud au cœur.",
      "Je me suis donc dit qu’il fallait aussi que je vous remercie, car je viens tout juste de réserver mon aller simple pour quitter la France. Après 5 ans de travail acharné, c’est un moment très symbolique pour moi.",
      "On a encore beaucoup de chemin à parcourir ensemble pour atteindre nos objectifs, mais j’ai compris une chose essentielle : ce n’est pas un sprint, c’est un marathon.",
      "Derrière nos écrans, on ne mesure pas toujours l’impact que nous avons sur la vie de nos clients, car tout cela reste souvent immatériel. Mais le rêve que je vais pouvoir réaliser cette année, c’est grâce à vous.",
      "J’aurai la chance de passer 4 mois en Asie, entre Bangkok et Kuala Lumpur, avant d’arriver à Abu Dhabi le 13 mars.",
      "Alors merci du fond du cœur à toute l’équipe du Funnel Club @Rémy Jupille @Geoffrey Bonniot et toutes les personnes qui travaillent à vos côtés, car sans vous, tout cela serait sûrement encore loin. Je vais enfin pouvoir honorer la promesse faite à ma femme il y a 5 ans : celle de vivre une vie de liberté.",
      "Merci aussi à @BUFFET Roland, pour ton soutien dans les moments plus difficiles. Je m’en souviendrai, et ma porte sera toujours grande ouverte pour toi — ainsi que pour tous les membres du Mastermind.",
      "(Heureux de vous accueillir si vous passez dans l’un de ces trois pays 🌏)",
      "Je ne suis pas très sentimental, donc je ne vais pas en dire plus, mais sachez que vous avez changé deux vies cette année : la mienne, celle de ma femme… et très bientôt, celles de mes futurs collaborateurs.",
      "🙏 Merci pour tout.",
    ],
  },
  {
    nom: "Laëtitia Miroux",
    niche: "Fondatrice Exportateurs Engagés - Méthode structurée, résultats export concrets",
    portrait: "/immersion/communaute/laetitia-miroux.jpg",
    titre: "Ce n’est plus une idée. Ce n’est plus un projet. C’est concret.",
    surligne: ["On est 4 personnes dont 3 membres !", "j’avais les “boules”."],
    paragraphes: [
      "@Rémy Jupille - @Geoffrey Bonniot - @Maxime LEGROS - bonsoir à toutes et tous",
      "Ce matin, j’ai donné mon tout premier coaching de groupe dans ma communauté “Les Exportateurs Engagés”.",
      "On est 4 personnes dont 3 membres ! Donc oui, c’est un petit début. Mais c’est un début réel. Et honnêtement, avant de commencer… j’avais les “boules”.",
      "Peur qu’il n’y ait rien à dire. Peur que ce soit vide. Peur que les membres ne parlent pas. Peur de ne pas savoir comment prendre le coaching en main.",
      "C’était mon premier.",
      "Finalement, j’ai structuré la session en trois temps :",
      "Présentation de chacun : pourquoi ils ont rejoint les Exportateurs Engagés et quelles sont leurs problématiques.",
      "Leurs retours sur leurs premières utilisations de mon espace membre.",
      "Leurs questions concrètes sur leurs problématiques actuelles.",
      "Résultat ? 1h03 de coaching et j’ai dû arrêter pour respecter le cadre d’une heure 😃.",
      "Les échanges étaient riches. Il y a eu beaucoup de questions. Les membres ont contribué aux réflexions des autres. On a même défini de futurs sujets que je vais intégrer dans mon espace membre. Et ça, c’est précieux💎.",
      "Je suis encore en offre bêta. Une partie est construite, mais pas tout. Donc leurs retours vont me permettre d’améliorer la plateforme, d’enrichir les contenus et d’ajuster l’offre au plus proche de leurs besoins réels.",
      "Ce matin, j’ai vraiment ressenti ce que ça veut dire : faire vivre un espace membre (même si ce n’est qu’un début). Ce n’est plus une idée. Ce n’est plus un projet. C’est concret. 😱",
      "Je suis très contente aussi de l’état d’esprit des trois premiers membres. Positifs, impliqués, avec une vraie envie d’avancer et de réussir leur projet d’exportation. Je suis donc RAVIE de la sélection de mes membres! Il y avait une vraie bonne ambiance, presque un mini-salon tellement nous étions peu nombreux.",
      "Et je sais que ma façon d’animer va évoluer avec le temps. Comme tout, ça s’apprend, ça se peaufine, ça se structure.",
      "Mais aujourd’hui, c’est une victoire. Une petite victoire peut-être en chiffres. Mais une grande victoire intérieure.",
      "Je souhaite à tous celles et ceux qui sont en train de construire leur offre de vivre ce moment-là. Et je me souhaite à moi-même de continuer, de recruter de nouveaux membres (intéressants, positifs, motivés et percutants) et de faire grandir cette communauté 😌.",
      "J’avance et ça fait plaisir à vivre.",
      "Merci Funnels Club pour le cadre et la méthode 😍.",
    ],
  },
  {
    nom: "Mohamed Ashad",
    niche: "Coach & Consultant pour restaurateurs",
    portrait: "/immersion/communaute/mohamed-ashad.jpg",
    titre: "mon webinar vient d’être validé",
    surligne: ["Merci les coachs 🙏"],
    paragraphes: [
      "J’aimerais partager avec vous une petite victoire, mon webinar vient d’être validé par @Geoffrey Bonniot .",
      "Si ça peut aider, pour le script j’ai utilisé un GPT personnalisé nourri de mes fiches, ainsi que les infos données par @Rémy Jupille. Une fois validé par le coach, je l’ai retapé pour l’adapter à l’oral. J’ai aussi regardé plusieurs webinaires et je m’en suis inspiré pour filmer (ton, montage, effets…)",
      "Merci les coachs 🙏",
      "vsl Mohamed v2.mp4",
    ],
  },
  {
    nom: "Marie Favre",
    niche: "thérapeute spécialisée en parcours PMA",
    portrait: null,
    titre: "ça y est, je viens tout juste de valider mes slides pour le webinaire",
    surligne: ["Merci à tous pour ce groupe et votre énergie."],
    paragraphes: [
      "Hello tout le monde !",
      "Je vous fais un petit coucou pour vous dire que j’avance… et que ça y est, je viens tout juste de valider mes slides pour le webinaire 🎉 ! Je m’apprêtais donc à tourner la vidéo, et  @Geoffrey Bonniot  m’a conseillé de venir jeter un œil à la version V6. Je pense que je vais suivre le nouveau process de la V6, même si je ne l’ai pas encore regardé dans le détail (promis, je m’y mets juste après 😅).",
      "J’espère que ça avance bien de votre côté aussi. Ici, je ne vais pas vous mentir : ça a été un sacré boulot pour en arriver là. Quand j’ai eu cette “brillante” idée de lancer un programme à distance, je croyais naïvement que le plus dur serait de l’avoir… l’idée 😅 Bon, spoiler : pas du tout.",
      "J’ai mis un an entier à construire mon programme, à y bosser quasi 8h par jour, tous les jours. Des sacrifices, beaucoup de remises en question, des doutes aussi, mais aujourd’hui le programme est là. Il est prêt. Mon espace membre ClickFunnels est finalisé. Le produit existe. Il est solide. Et maintenant… il est temps de le vendre.",
      "Merci à tous pour ce groupe et votre énergie. Et bon courage à chacun·e dans vos étapes respectives 🙌",
    ],
  },
  {
    nom: "Alexandra Schlienger",
    niche: "Sophrologue - D.U \"Psychisme face à la naissance\" Université Paris Cité",
    portrait: "/immersion/communaute/alexandra-schlienger.jpg",
    titre: "tunnel terminé dans son ensemble",
    surligne: [],
    paragraphes: [
      "Salut @Geoffrey Bonniot, j’espère que tu vas bien 😀",
      "Un post pour te tenir informé, de mon côté tout est ok sur :",
      "1) tunnel terminé dans son ensemble / mails ok voici son lien :",
      "Préparez votre accouchement sereinement grâce à la Sophrologie. Gérez vos émotions, construisez votre projet de naissance et vivez la maternité en confiance avec la Sophrologie en ligne.(pas peu fière d’avoir tout fait en autonomie 🥰)",
      "2) intégration client ok, contrat ok",
      "3) cartographie ok (me reste encore 1h de boulot dessus car j’ai repris plusieurs modules)",
      "4) espace membre ok, modules créés ok",
      "Comme on n’est jamais satisfait de soi, j’aurai aimé aller plus vite mais je bosse très tôt avant mes journées de boulot et la gestion de mes enfants 😃 Je suis déjà contente que tout soit prêt.",
      "Par contre pour l’offre béta, après avoir repris l’ensemble des modules, je monte son prix de départ à 450€, 300€ me semble trop faible pour son prix même de démarrage.",
      "J’ai changé mes heures de travail, je devrai réussir à assister aux coaching à partir de fin-novembre/début décembre pour le lancement des pubs 😊",
      "Passe une belle journée, à très vite pour l’évaluation des pubs 🤩 et le prochain tournage des leçons !",
    ],
  },
  {
    nom: "Catherine Dumont",
    niche: "Consultante pour entrepreneurs indépendants",
    portrait: "/immersion/communaute/catherine-dumont.jpg",
    titre: "J’ai beaucoup appris durant cette étape de créer son tunnel",
    surligne: ["J’en suis encore au début, mais j’apprends énormément!"],
    paragraphes: [
      "Bonjour Geoffrey et Rémy,",
      "J’ai beaucoup appris durant cette étape de créer son tunnel et je voulais vraiment te remercier Rémy pour la qualité de la formation. J’en suis encore au début, mais j’apprends énormément!",
      "Voilà, j’ai fini mon tunnel et j’aurais bien aimé avoir votre retour dessus.",
      "Voici les liens des différentes pages:",
      "https://tunnel.gestion-s-mesure.ch/inscription",
      "https://tunnel.gestion-s-mesure.ch/visionnage",
      "https://tunnel.gestion-s-mesure.ch/reservation",
      "https://tunnel.gestion-s-mesure.ch/confirmation",
      "A très vite.",
    ],
  },
  {
    nom: "Amaury Aguado",
    niche: "Investir autrement",
    portrait: "/immersion/communaute/amaury-aguado.jpg",
    titre: "Je partage ici mon premier retour d’expérience sur un appel de qualification",
    surligne: ["·       le rôle du R1 n’est pas de convaincre, mais de qualifier"],
    paragraphes: [
      "Hello @Geoffrey Bonniot, @Rémy Jupille et vous tous,",
      "Je partage ici mon premier retour d’expérience sur un appel de qualification (R1).",
      "Le prospect arrive par une publicité, assiste au webinar, puis réserve un premier rendez-vous via Calendly pour 10h30.",
      "À ce stade, rien d’inhabituel.",
      "La veille du rendez-vous, n’ayant pas de reçu la confirmation du RDV de sa part, je lui envoie un message simple via whatsapp et cadré pour vérifier que le créneau est toujours OK.",
      "Le message est bien reçu… mais pas lu.",
      "Dans la soirée, je constate qu’il réserve un second créneau le même jour, cette fois à 11h30, tout en conservant celui de 10h30.",
      "Toujours aucun message lu.",
      "Aucune confirmation explicite pour l’un ou l’autre.",
      "Le matin du rendez-vous, je prends alors une décision importante : remettre de la structure là où il y a du flou.",
      "Je choisis de conserver un seul créneau, le plus récent, et j’en informe le prospect de manière factuelle via whatsapp : je l’appellerai à 11h30, sauf indication contraire de sa part.",
      "À 11h30 pile, j’appelle.",
      "Une seule tentative.",
      "Il ne décroche pas.",
      "Et c’est là que l’apprentissage commence réellement.",
      "Pas de rappel.",
      "Pas d’insistance.",
      "Pas de poursuite émotionnelle.",
      "Je clôture simplement, en lui envoyant un mail en laissant l’initiative revenir au prospect s’il souhaite reprogrammer.",
      "Pour l’instant aucun retour et mes messages whatsapp sont toujours non lu.",
      "Mais loin de le vivre comme un échec, ce premier R1 a été extrêmement formateur. J’ai beaucoup discuté avec l’Esprit Closing et il m’a rappelé plusieurs fondamentaux essentiels :",
      "·       le silence est une information",
      "·       un no-show n’est pas un rejet, mais un indicateur de niveau d’engagement",
      "·       le rôle du R1 n’est pas de convaincre, mais de qualifier",
      "·       quand il y a du flou, c’est à l’offreur de remettre du cadre",
      "·       mieux vaut perdre un prospect que perdre sa posture",
      "Je suis finalement content d’avoir vécu ce scénario dès le début.",
      "Il m’a permis de tester concrètement le cadre, la méthode, et surtout mon état d’esprit.",
      "La première expérience n’est pas toujours spectaculaire. Mais elle est souvent la plus structurante.",
      "On continue…",
      "Bien à vous,",
    ],
  },
  {
    nom: "Armel Quenecant",
    niche: "Conseiller immobilier",
    portrait: "/immersion/communaute/armel-quenecant.jpg",
    titre: "je souhaitais prendre quelques minutes pour vous donner des nouvelles",
    surligne: ["Merci d'avance pour vos conseils et heureux d'être de retour parmi vous !"],
    paragraphes: [
      "Bonjour à tous et bonjour aux coachs,",
      "Après plusieurs mois d'absence, je souhaitais prendre quelques minutes pour vous donner des nouvelles et vous partager l'évolution de mon projet.",
      "Lorsque j'ai rejoint Funnels Club, mon objectif était de créer une offre d'accompagnement premium autour de l'investissement financier, en complément de mon activité de conseiller en investissements financiers.",
      "Depuis, les choses ont évolué.",
      "Face aux enjeux d'acquisition de clients pour mon cabinet et à la nécessité de générer du chiffre d'affaires plus rapidement, j'ai lancé en parallèle une activité de mandataire immobilier indépendant. Les débuts ont été exigeants, mais les premiers résultats arrivent et cela m'a amené à revoir certaines de mes priorités.",
      "Aujourd'hui, mon objectif principal est de développer cette activité immobilière grâce au digital.",
      "Je suis convaincu que les compétences enseignées au sein de Funnels Club peuvent m'aider à franchir un cap important, notamment sur les sujets suivants :",
      "✅ Développer une vraie compétence en création de contenu vidéo (mon principal défi aujourd'hui)",
      "✅ Construire une présence forte sur les réseaux sociaux, avec un focus particulier sur Instagram dans un premier temps",
      "✅ Mettre en place un système d'acquisition performant (direct webinar, lead magnet, tunnel, prise de rendez-vous, nurturing, etc.)",
      "✅ Développer une marque personnelle locale capable de me différencier face à des acteurs historiques peu présents en ligne",
      "Concernant mon ancien projet, je mets pour le moment de côté la création d'une formation grand public sur l'investissement.",
      "En revanche, à moyen terme, je souhaite également structurer un parcours de formation interne destiné à accompagner de futurs conseillers souhaitant développer la même activité que moi. Ce n'est pas ma priorité immédiate, mais c'est une vision que je souhaite construire progressivement.",
      "Mon objectif aujourd'hui est donc simple : utiliser les méthodes et les outils de Funnels Club pour bâtir un système d'acquisition autour de mon activité immobilière avant d'élargir progressivement l'écosystème.",
      "Je serais ravi d'avoir vos retours sur cette orientation et, selon vous, sur les priorités à travailler dans les prochains mois.",
      "Merci d'avance pour vos conseils et heureux d'être de retour parmi vous ! 🤝",
    ],
  },
  {
    nom: "Laetitia Borel",
    niche: "Coach Thérapeute",
    portrait: "/immersion/communaute/laetitia-borel.jpg",
    titre: "Il y a 2 semaines à peine, je me suis inscrite à Funnels Club",
    surligne: ["Il y a 2 semaines à peine, je me suis inscrite à Funnels Club et j’ai écouté quelques vidéos proposées de présentation…"],
    paragraphes: [
      "Hello à tous,",
      "Il y a 2 semaines à peine, je me suis inscrite à Funnels Club et j’ai écouté quelques vidéos proposées de présentation… mais j’avais du mal à plus avancer car j’étais en cours de validation d’une formation en parallèle. J’ai cette tendance à l’éparpillement et comme à mon habitude même si je devais réviser, j’ai aussi pas mal flané notamment sur les vidéos de Remy qui m’ont énormément plu, et j’ai compris aussi que le mindset était important, qu’être un prestataire de services c’est pas forcément comme ça qu’on est le plus rentable, et qu’il est important pour l’avancement d’éviter l’éparpillement pour rester focus.",
      "Alors je suis ravie d’avoir passé une étape de compréhension qui est crucial pour poursuivre dans le bon état d’esprit et mettant libérer d’une évaluation d’une formation je peut cette fois-ci être plus focus.",
      "Je voulais aussi remercier Remy car quand je l’écoute je me sens motivée, et je comprends l’état d’esprit que nous devons tous avoir, c’est une base auquelle je n’avais pas conscience avant.",
      "Bonne journée à tous le club des funnelois.",
      "Laetitia",
    ],
  },
  {
    nom: "Igor Hotton",
    niche: "Coach MLM",
    portrait: null,
    titre: "C’est avec beaucoup d’enthousiasme que j’interviens ici",
    surligne: ["C’est avec beaucoup d’enthousiasme que j’interviens ici pour la premiere fois 😋"],
    paragraphes: [
      "Bonjour à tous et toutes,",
      "C’est avec beaucoup d’enthousiasme que j’interviens ici pour la premiere fois 😋",
      "Igor Hotton , je suis coach avec une spécialité en Marketing Relationnel et je vous aide à prendre soin de votre santé et de vos finances grâce aux bienfaits qu’apportent des compléments alimentaires, entre autres.",
      "Mon objectif ici est de créer une formation MLM afin de partager mon expérience de plus de 20 ans dans ce domaine et former et developper ainsi une équipe solide avec l’aide du Funnels club.",
      "Voilà en résumé ma direction principale en ce 1er jour de formation.",
      "Remerciements à Remis et son équipe car vous dégagez tous et toutes une belle énergie porteuse et positive.",
    ],
  },
  {
    nom: "Linn",
    niche: "Styliste et  Conseillère en image",
    portrait: "/immersion/communaute/linn.jpg",
    titre: "l’un des meilleurs espaces de formation dans lequel j’ai été",
    surligne: ["pleutre dans 2 ou 3 mois , je ne sais pas", "Merci pour votre bienveillance et votre guidance."],
    paragraphes: [
      "Hello à tous et très bonne année !",
      "Je me réveille un peu tard pour un message collectif (on est déjà mi-janvier 😅) mais je tenais vraiment à vous la souhaiter.",
      "Un petit mot aussi pour remercier les coachs : @Rémy Jupille, @Geoffrey Bonniot, @Maxime LEGROS, @Ludivine et  @Kylian Baude  qui m’a closé il y a déjà un moment, même si de base je n’avais pas prévu de commencer tout de suite ( trop de travail avant de vendre) au final c’était une très bonne décision 😄 merci à toi.",
      "Le Funnel Club a vraiment compté dans mon année 2025, même si je ne suis pas très “communauté” de base 😅 team introverti 🤭",
      "J’ai appris beaucoup de choses  sur le business mais aussi sur moi, sur la manière de construire une offre, de structurer un produit, etc.",
      "Je n’ai pas été très active dans les coachings cette année, parce que j’ai passé beaucoup de temps en construction :",
      "– structuration de mon offre",
      "– création d’un book de plus de 100 pages",
      "– 60+ petites vidéos pour mes clientes et mon espace",
      "– définition de ma cible 🎯",
      "– tunnel, hébergement, et début de ma chaîne YouTube",
      "– relance de mon Instagram",
      "Donc 2025 = maturation",
      "2026 = expansion ✨",
      "Pour 2026, objectif : premiers clients et beaucoup d’organique au premier trimestre, puis pub + closing une fois que la machine tourne avant 2027, je l’espère.",
      "J’ai beaucoup écouté les coachings cette année, j’ai l’impression de connaître @Virak CHHUOR, @Sacha COHEN et @Jérôme et @François DAOUD alors qu’on ne s’est jamais parlé 😂 (et @Tatiana Moreau + @Clemence Privé  aussi !)",
      "Merci pour votre bienveillance et votre guidance.",
      "C’est sincèrement l’un des meilleurs espaces de formation dans lequel j’ai été. I swear 🫶🏻",
      "Je vous souhaite une très belle année 2026, pleine  de réussite pro et perso 😄",
      "Au plaisir de vous retrouver dans d’autres contextes cette année ! pleutre dans 2 ou 3 mois , je ne sais pas",
      "Linn",
    ],
  },
  {
    nom: "Christophe et Dominique Crapez",
    niche: "High Impact Mindset",
    portrait: "/immersion/communaute/christophe-dominique-crapez.jpg",
    titre: "Rejoindre Funnels Club a été la meilleure décision professionnelle de ma vie !",
    surligne: ["Merci infiniment pour votre bienveillance et votre patience."],
    paragraphes: [
      "Coucou l’équipe,",
      "Je découvre la nouvelle version de Funnels Club et je la trouve incroyable ! Je suis ravie de faire partie de cette aventure, car je sais à quel point il est extraordinaire de partager son savoir avec les autres, et vous le faites à merveille. Rejoindre Funnels Club a été la meilleure décision professionnelle de ma vie !",
      "Sachez aussi que je ne me suis pas éclipsée pour abandonner. Après la réalisation de mon webinar, j’ai enchaîné directement sur la création de mon programme et je viens tout juste de terminer les vidéos aujourd’hui. Christophe gère maintenant la logistique, ce qui nous permettra de nous lancer dans le courant de la semaine prochaine. Nous aurons donc le plaisir de vous retrouver très bientôt pour la pub et le closing !",
      "Merci infiniment pour votre bienveillance et votre patience. Même si, au fond, aucun mot ne suffira jamais à vous remercier, Christophe et moi vous sommes profondément reconnaissants. Grâce à vous, notre projet prend enfin forme. MERCI!",
      "Dom et Chris",
    ],
  },
  {
    nom: "Jacques Bouchard",
    niche: "La mobilité émotionnelle",
    portrait: "/immersion/communaute/jacques-bouchard.jpg",
    titre: "Je ressens une grande gratitude envers Rémy, son équipe",
    surligne: ["Encore bravo et merci."],
    paragraphes: [
      "Bonjour à toutes et à tous,",
      "Je ressens une grande gratitude envers Rémy, son équipe, vous qui les avez rejoints, et moi-même pour ce choix. Ce sentiment ne relève pas de l’« effet lune de miel » : inscrit depuis début 2024 et connaissant la version précédente, je mesure la qualité de la progression. Les visuels, les contenus, l’ensemble : tout a franchi un cap remarquable. Je viens de terminer Modèle et État d’Esprit et je vais reprendre le parcours depuis le début.",
      "Bravo à Rémy pour son exigence et sa recherche d’excellence, et bravo à toutes celles et ceux qui ont contribué à cette nouvelle version.",
      "Ce qui me touche particulièrement, c’est que tu incarnes un modèle sain, encore plus clairement qu’auparavant. Tu partages ton expérience de manière authentique, en reliant corps, esprit et action comme moteurs de réussite, avec des preuves concrètes à l’appui. Tu es exemplaire tout en restant humble et généreux : tu encourages à te prendre comme modèle tout en rappelant que chacun porte ses propres lunettes et reste responsable de ses choix.",
      "Tu offres un espace sécurisant, que l’on retrouve aussi chez tes collaborateurs. Tu reconnais la valeur de chacun, même débutant, et tu sais percevoir et encourager notre potentiel unique. Funnels Club reflète cette exemplarité : un ensemble cohérent, beau et de grande qualité.",
      "Dans le module État d’Esprit, ta générosité m’a particulièrement marqué. Partager ta perception des ressorts de la réussite tout en reconnaissant la diversité des points de vue démontre une véritable humilité. Tu ne juges pas ceux qui empruntent d’autres chemins : tu proposes, tu éclaires, et chacun accueille en conscience ce qu’il souhaite garder.",
      "Encore bravo et merci. / /",
    ],
  },
  {
    nom: "Arthur",
    niche: "Coach santé et nutrition P.N1",
    portrait: "/immersion/communaute/arthur.jpg",
    titre: "Je tenais à te remercier sincèrement pour les récentes mises à jour",
    surligne: ["Merci également pour ton dévouement et ton implication."],
    paragraphes: [
      "Salut @Rémy Jupille Je tenais à te remercier sincèrement pour les récentes mises à jour dans Funnels Club, en particulier le module État d’esprit et la leçon sur le modèle. Ce n’est pas une surprise : je savais déjà que ce que j’apprécie profondément dans Funnels Club, c’est cette capacité unique à nous accompagner aussi bien sur le plan business que sur le plan humain. Depuis hier, j’ai commencé à regarder les vidéos du module État d’esprit, et je ne fais que recevoir claque après claque. Chaque contenu me pousse à réfléchir, à me remettre en question, et surtout à grandir. Merci également pour ton dévouement et ton implication. On sent que tu tiens réellement à notre réussite, et cela se reflète dans la qualité du contenu, le souci du détail et la richesse des enseignements. Je suis entièrement d’accord avec toi : personne ne nous apprend à devenir entrepreneur. Et pourtant, c’est essentiel, car pour construire un business solide, il faut d’abord être ALIGNÉ. Être aligné, c’est lorsque ton identité intérieure, tes valeurs, tes intentions et tes ambitions sont en harmonie avec tes actions. Quelqu’un qui veut être entrepreneur, mais qui procrastine, doute de lui, évite les décisions et s’autosabote n’est pas aligné. Il veut le résultat, mais ne pense pas, ne parle pas et n’agit pas comme une personne capable de l’accueillir. Et tant qu’il n’incarne pas cette posture, il avance à vide. Mais grâce à ce nouveau module Mindset, à la fois finement structuré et transmis avec beaucoup de clarté, je me sens plus confiant, mieux préparé, mieux équipé, avec une vision plus ancrée de ce que cela implique d’entreprendre et de bâtir un business. Le mindset, la psychologie, la productivité, le focus, la santé physique comme mentale prennent enfin tout leur sens dans mon parcours. Cette mise à jour n’a fait que renforcer ma conviction : rejoindre Funnels Club a été l’une des meilleures décisions que j’ai prises l’an dernier, autant sur le plan entrepreneurial que personnel. Franchement, chapeau à toi et à toute l’équipe pour ce BEAU travail !🙌",
    ],
  },
  {
    nom: "Olivier Caetano",
    niche: "J'aide les entrepreneurs qui plafonnent à voir ce qui les bloque et à faire repartir leur chiffre | 24 ans d'expérience | Octocube",
    portrait: "/immersion/communaute/olivier-caetano.jpg",
    titre: "Vos apports sont à la fois structurants, concrets et immédiatement actionnables",
    surligne: ["Que ces fêtes de fin d’année vous apportent sérénité, joie et inspiration pour les mois à venir."],
    paragraphes: [
      "Chers @Geoffrey Bonniot, @Ludivine, @Rémy Jupille, @Kylian Baude, autres membres de l’équipe que je connais pas encore,",
      "Je tenais à vous adresser ce message afin de vous remercier sincèrement pour la qualité et la valeur du contenu partagé dans le cadre de la mise en place du tunnel de vente. Vos apports sont à la fois structurants, concrets et immédiatement actionnables, constituant un véritable levier de progression.",
      "Je souhaite également souligner la pertinence de vos retours ainsi que votre grande réactivité, particulièrement précieuses dans une phase aussi stratégique. Même si la première vente n’est pas encore intervenue, la dynamique est bien engagée et je  poursuis le travail avec détermination et confiance dans la suite.",
      "À l’approche de la fin d’année, je souhaite à toute l’équipe et à toute la communauté une très belle coupure, propice au repos et au ressourcement. Que ces fêtes de fin d’année vous apportent sérénité, joie et inspiration pour les mois à venir.",
      "Au plaisir de poursuivre cette collaboration dans les prochaines étapes.",
      "Bien cordialement, Olivier",
    ],
  },
  {
    nom: "Frédéric Feller",
    niche: "Coach/Formateur - Formation \"ImpacZen\", pour une prospection plus humaine.",
    portrait: "/immersion/communaute/frederic-feller.jpg",
    titre: "plusieurs idées fortes m’ont particulièrement marqué",
    surligne: ["Identifier mes biais cognitifs m’aide à reprendre le contrôle de mes décisions et à éviter de subir mes automatismes."],
    paragraphes: [
      "Bonjour à tous,",
      "En travaillant ce cours , plusieurs idées fortes m’ont particulièrement marqué :",
      "Mon corps est mon premier capital : sans énergie physique, il n’y a ni productivité durable, ni clarté mentale.",
      "Ma réalité n’est pas absolue : elle est filtrée par mes croyances, mes émotions et mes biais. Plus je prends conscience de ces filtres, plus je peux élargir mon champ des possibles.",
      "Ce sont les petits pas réguliers qui créent les grandes avancées, bien plus que les efforts ponctuels et intenses.",
      "Identifier mes biais cognitifs m’aide à reprendre le contrôle de mes décisions et à éviter de subir mes automatismes.",
      "Enfin, j’ai choisi d’adopter de nouvelles croyances : la régularité prime sur l’intensité, le progrès est plus important que la perfection, et l’argent est une ressource abondante.",
      "👉 Ce que je retiens avant tout, c’est que mon calme et ma constance constituent de véritables leviers de performance entrepreneuriale.",
      "Veuillez trouver ci-jointes “la fiche de réflexion”, La routine sur mes croyances que je viens de mettre en place.",
      "Hâte d’avoir vos retours.",
      "Rituel sur mes croyances - Frédéric Feller.docxFiche de réflexions Frédéric Feller.docxBon dimanche.",
      "Frédéric",
    ],
  },
];
