/**
 * Le mur de la communauté : ce que les membres écrivent dans le groupe Circle.
 *
 * **Rien n'est écrit ici, tout est recopié.** Les `paragraphes` sont le post
 * entier, tel que l'API Circle le rend, découpé en paragraphes et rien de plus.
 * Pas un mot ajouté, pas une phrase reformulée, pas une coquille corrigée :
 * « je n'aurai pas conçu » de Guy est son texte, et c'est comme ça qu'il se
 * publie. C'est la règle des transcriptions d'entretien, et pour la même
 * raison : ce sont les mots de vraies personnes.
 *
 * **Le post entier et non un extrait**, sur demande de Rémy. Un extrait oblige
 * à choisir la phrase qui vend le mieux, ce qui est une façon d'écrire à la
 * place de quelqu'un sans en avoir l'air.
 *
 * **Les dix-neuf posts sortent d'un parcours des 3 768 posts de la communauté**,
 * pas d'une sélection à l'œil. Les rediffusions et les posts de l'équipe ont
 * été écartés, les 492 récits de membres notés sur l'engagement, les marqueurs
 * de récit et de gratitude, puis les meilleurs relus un par un.
 *
 * **Aucun ne donne le prix de nos offres.** C'était la consigne de Rémy. Les
 * montants qui restent sont ceux que les membres gagnent, jamais ce qu'ils ont
 * payé.
 *
 * **Pas de lien vers le post d'origine**, sur demande de Rémy : le groupe est
 * privé, donc le lien mènerait un visiteur non membre à une page de connexion
 * Circle, c'est-à-dire hors du tunnel et dans une impasse. C'est vérifié, pas
 * supposé : un clic de test a bien atterri sur `login.circle.so`.
 *
 * **Ni étoiles, ni compte de réactions.** La carte relevée chez TrendTrack
 * porte cinq étoiles ; personne ici n'a noté Funnels Club, ce sont des posts de
 * communauté et pas des avis notés, et en afficher serait faire dire à
 * quelqu'un ce qu'il n'a pas dit. Les réactions du post avaient pris cette
 * place, parce qu'elles étaient vraies ; Rémy les a retirées, un nombre de
 * cœurs n'apprenant rien à qui découvre la page.
 *
 * **Le `titre` est un extrait, pas un résumé.** C'est une phrase du post,
 * recopiée mot pour mot et vérifiée contre la source, choisie pour donner envie
 * de lire le reste. Écrire un titre par-dessus le texte de quelqu'un reviendrait
 * à lui prêter une intention.
 *
 * **La `niche` vient du profil Circle de la personne**, son `headline`, et de
 * nulle part ailleurs. Trois membres n'en ont pas renseigné : leur carte
 * n'affiche rien sous leur nom. Deviner « coach » ou « formateur » à la lecture
 * de leur post serait leur inventer un métier. Un `headline` qui ne fait que
 * recopier le nom de la personne est écarté au passage : il n'apprend rien.
 *
 * **Les portraits sont ceux de Circle**, servis par nous : une page qui charge
 * ses avatars sur `app.circle.so` fait payer à chaque visiteur une résolution
 * DNS de plus, et ces adresses sont des redirections signées qui expirent.
 *
 * **`surligne` ne change pas le texte, il le désigne.** Chaque entrée est une
 * sous-chaîne exacte du post, vérifiée par comparaison contre la source, et le
 * rendu ne fait que l'envelopper dans un `mark`. C'est la seule façon de
 * surligner sans réécrire : un passage « mis en avant » qu'on aurait reformulé
 * pour qu'il tienne sur une ligne serait un passage inventé.
 *
 * **Les réponses viennent de l'API, une requête par post.** La v1 de Circle
 * **ignore la pagination** sur ses commentaires : elle rend les cinq cents
 * mêmes à chaque page, ce qui donnait trente mille lignes pour cent
 * cinquante-quatre posts distincts. Le filtre `post_id`, lui, marche. Les
 * réponses de plus de sept cents caractères sont écartées : ce sont des
 * échanges techniques avec un coach, pas des encouragements.
 *
 * **Les noms de famille cités dans les textes ne sont pas retirés d'ici**, mais
 * à l'affichage, par `lib/anonymat.ts`, avec les adresses. Une donnée déjà
 * caviardée ne se vérifie plus contre sa source.
 *
 * **À valider par Rémy, personne par personne.** Ces dix-neuf-là n'ont pas donné
 * leur accord pour figurer sur une page publique : ils ont écrit dans un groupe
 * privé. Un post de communauté n'est pas un témoignage cédé.
 */
export const murCommunaute: readonly {
  nom: string;
  /** Le métier, lu dans le `headline` du profil Circle. `null` s'il est vide. */
  niche: string | null;
  /** `null` quand Circle ne sert pas de portrait : la carte porte l'initiale. */
  portrait: string | null;
  /** Une phrase du post, mot pour mot, qui sert de titre à la carte. */
  titre: string;
  /** Les passages à surligner dans le corps, sous-chaînes exactes du post. */
  surligne: readonly string[];
  /** Le post entier, paragraphe par paragraphe, mot pour mot. */
  paragraphes: readonly string[];
  /** Les réponses des autres membres, dans l'ordre où elles ont été écrites. */
  reponses: readonly { nom: string; texte: string }[];
}[] = [
  {
    nom: "François Daoud",
    niche: "Professeur de guitare",
    portrait: "/immersion/communaute/francois-daoud.jpg",
    titre: "les choses ont complètement explosé cette semaine",
    surligne: ["Et j’ai bien fait."],
    paragraphes: [
      "Bonjour à tous,",
      "Aujourd’hui j’avais envie de vous partager mes aventures depuis quelques mois.",
      "Après un été assez calme et un petit moment de stress cet été, les choses ont complètement explosé cette semaine … et c’est dingue.",
      "Bref, je vous raconte !",
      "Pour recontextualiser l’histoire :",
      "J’ai rejoint le Funnels Club en Avril,",
      "En mai, je lance mon offre premium,",
      "Mon offre est une formation impro guitare semi-professionnalisante.",
      "Déjà au début quand je suis arrivé, quand Rémy m’a parlé de proposer une offre à 2000€ minimum, j’étais un peu décontenancé. Même dans mon école de musique physique où la prestation était assez étoffée je ne proposais pas un tel tarif (plutôt autour de 900€).",
      "Finalement, je me suis exécuté, et j’ai appliqué les conseils du coach.",
      "Dès ce mois de mai, sur 10~15 appels, j’en signe 4.",
      "J’ai trouvé ça dingue, d’autant plus que je facture 2000~2500€ la prestation…",
      "Serait-ce la chance du débutant ?",
      "Ayant une chaine Youtube active depuis 2 ans, je me disais qu’il s’agissait peut-être que des prospects très chauds… Et que ça va se dégonfler…",
      "Le mois de Juin a été moins convaincant, je n’ai signé que 2 personnes sur 22 appels.",
      "Ca reste toutefois ~4ke. Donc c’est chouette, mais il y avait ce petit goût de “zut ! Ca n’a pas fonctionné comme j’espérais, ça s’essouffle déjà!”",
      "Et là, arrivent les mois de Juillet et Aout.",
      "Ce sont 2 mois assez difficiles.",
      "1 signature en Juillet, 1 autre en Aout… et c’est tout. Pourtant 24 appels.",
      "Vers la mi-août, suite à un événement un peu compliqué émotionnellement, j’ai commencé à stresser…",
      "Et mon taux de closing était assez bas…",
      "J’ai expliqué mon point à Geoffrey et Rémy, avec cette envie de casser mes prix pour closer davantage.",
      "Pourquoi casser les prix ?",
      "Parce que je voyais bien que c’était constamment à cette étape là que ça coinçait lors des closings.",
      "Donc, à ce stade là (~20 août), les chiffres disaient :",
      "13% de closing global,",
      "mais toutefois…  6,7% de closing sur les 8 dernières semaines (je parle des 8 semaines qui précédaient le mois d’Août)",
      "2 signatures entre juillet et ~20 aout",
      "l’envie de casser les prix pour les descendre à 1400€ au lieu de 2000€.",
      "Et alors que j’allais basculer, je me suis quand même dit que j’allais en parler aux coachs. Chose que j’ai faite (quand même …)",
      "Et j’ai bien fait.",
      "Rémy et Geoffrey ont attiré mon attention sur plein de petits points, et m’encourageaient à garder le cap même si c’était dur, de ne pas me laisser happer par les émotions (ces fameuses émotions…).",
      "D’ailleurs, ils ont également attiré mon attention sur la période, et sur la fausseté de mon calcul (je regardais les 8 dernières semaines au lieu de regarder les 3~4 derniers mois).",
      "Bref, j’ai joué le jeu jusqu’au bout en me disant qu’il faut suivre les conseils et stratégies des coachs.",
      "Finalement, moins de 10 jours plus tard, la machine s’emballe !",
      "Les résa d’appels pleuvent, et j’en arrivent à aujourd’hui :",
      "J’ai signé 5 personnes en 7 jours (9100€).",
      "J’ai plein d’appels de programmés,",
      "D’autres R2 arrivent,",
      "Nous ne sommes que le 5 septembre,",
      "Et j’ai l’impression qu’atteindre 12 à 20ke ce mois ne sera qu’une formalité !",
      "Bref, je ne m’emballe pas trop, mais je suis passé de 1 mois de tréso à 4 mois ! Là, comme ça, en 1 semaine … C’est juste dingue 🙏🙏🙏",
      "Ca y est, la machine s'emble s’emballer 🚀",
      "Moralité de l’histoire : Les coachs ont toujours raison + il faut garder le cap parce que quand ça s’emballe, ça s’emballe !",
      "Edit à j+2 : +4000€ ! Ce qui amène ce mois de septembre à 13100€… et nous ne sommes que le 06/09. C’est juste dingue ce qui se passe…",
    ],
    reponses: [
      { nom: "Olivier CAETANO", texte: "Super témoignage, tellement encourageant, merci beaucoup !" },
      { nom: "Many Soliman", texte: "Bravo à toi françois. Tu ne récoltes que ce que tu mérites 😁. Je te souhaites la réussite dans ton projet ( et sa a l’air de demarrer😎) ton expérience est inspirante. Nous sommes des êtres émotionnels et cela nous freine. Heureusement que les coachs sont la pour nous remettre les pieds sur terre. Many" },
      { nom: "Thomas Venet", texte: "Bravo à toi ! c’est top👏" },
      { nom: "Neyla Mudi", texte: "Merci pour ton témoignage! C’est très encourageant. Est-ce que je peux te demander ton budget en pub  @François DAOUD?" },
      { nom: "François DAOUD", texte: "@Neyla Mudi Hello ! Merci pour ton retour. Oui bien sur, actuellement je suis à 15€/jour pour le moment :-)" },
      { nom: "François DAOUD", texte: "@Thomas Venet Merci Thomas ! Trop content !" },
      { nom: "François DAOUD", texte: "@Many Soliman Oh que oui … Pourtant je pensais être rôdé côté émotions liées au business. En fait, pas du tout. On a vraiment besoin d’un accompagnement pour franchir des paliers, sinon nos propres émotions sont nos propres limites…" },
      { nom: "François DAOUD", texte: "@Olivier CAETANO Merci Olivier !" },
      { nom: "François DAOUD", texte: "Quelle folie… entre l’écriture du post (hier) et aujourd’hui = +4000€ …" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations @François DAOUD ! Tes résultats sont mérités j’ai hâte de voir ce que donnent les chiffres à la fin de ce mois ! Et ce n’est que le début ! 🚀" },
      { nom: "Geoffrey Bonniot", texte: "@François DAOUD On ne t’arrête plus ! 🚀" },
      { nom: "Linn 🦋", texte: "Bravo François 😉" },
      { nom: "Chrystel Gerard", texte: "Bravo François, tu as bien fait de persévérer. Ce n’est que le début 😀" },
      { nom: "Neyla Mudi", texte: "@François DAOUD Merci c’est d’autant plus encourageant qu’on a pas besoin de mettre des masses. Merci pour l’info. Bonne continuation" },
      { nom: "Nicolas Havenith", texte: "Bravo @François DAOUD d’avoir gardé ta ligne de conduite ! Les résultats sont là !" },
      { nom: "Bruno Beuret", texte: "Message vocal" },
      { nom: "François DAOUD", texte: "@Neyla Mudi Hello Neyla, pour le moment mes ventes viennent plutôt de l’organique (Youtube). La partie pub m’aide à me constituer une belle base mail et ça va surement se décanter dans les semaines/mois à venir. Mais effectivement, pas besoin d’un gros budget pub pour démarrer puisque l’organique permet de choper ses premiers clients. De mon côté, organique ou publicité j’ai l’impression qu’il faut quelques mois pour que la machine commence à prendre !" },
      { nom: "François DAOUD", texte: "@Geoffrey Bonniot haha j’en suis le premier surpris (je te remercierai jamais assez pour tout ça Geoffrey !!!)" },
      { nom: "François DAOUD", texte: "@Geoffrey Bonniot Merci ! Moi aussi, j’ai bien l’impression que les 16~20ke sont désormais atteignables ! Le “ce n’est que le début” me donne des frissons !" },
      { nom: "François DAOUD", texte: "@Linn 🦋 Hello Linn, merci !" },
      { nom: "François DAOUD", texte: "@Chrystel Gerard Merci beaucoup pour tes encouragements !" },
      { nom: "François DAOUD", texte: "@Nicolas Havenith Merci pour tes encouragements ! Les émotions sont vraiment traitres parfois… j’ai failli basculer à un moment. Heureusement que j’ai eu le réflexe d’en parler aux coachs !" },
      { nom: "François DAOUD", texte: "@Bruno Beuret Message vocal" },
      { nom: "Curier Davy", texte: "Bravo à toi @François DAOUD je prends plaisir à suivre ton aventure et cela m’inspire beaucoup ☺️." },
      { nom: "Nathalie Rossa Tisseau", texte: "Félicitations François !!!" },
      { nom: "Bruno Beuret", texte: "@François DAOUD Merci pour ton retour précieuse, je vais prendre en compte. Par contre, tu à vu la mauvaise chaîne YouTube 🙂 celle que tu a vu, ma chaîne pour poser mes vidéo que je mets sur mon site artistique. Ma vrai chaîne est : https://www.youtube.com/channel/UCbRUTeXWpJF7O51Uhpm5oZA Plus axé tuto / leçon Photoshop. Mais j’ai quand même bien noté se que tu ma dit sur YouTube. 😉 Merci infiniment." },
      { nom: "Mario Gaudreault", texte: "Merci François pour ce témoignage, très apprécié." },
      { nom: "Sophie Boeuf Brunner", texte: "ouha merci ton témoignage ! c’est hyper motivant !" },
      { nom: "Kylian Baude", texte: "Félicitation @François DAOUD, c’est génial ! 🚀" },
      { nom: "Mauro Di Fino", texte: "C’est génial François, félicitations! Ton témoignage est encourageant et me rassure sur le fait qu’il faut partager nos doutes avec les coachs." },
      { nom: "Ilyasse Setti", texte: "Félicitations François ! Super inspirant ton message… Je te souhaite plein de succès." },
      { nom: "François DAOUD", texte: "@Bruno Beuret Ah ou effectivement ce n’est plus le même nombre du vues ! C’est excellent. Courage pour la suite, il n’y a aucune raison que ça marche pour moi et pas pour toi. Je radote, mais ce qui m’a le plus aidé, ce sont les interactions et le partage auprès des coachs !" },
      { nom: "François DAOUD", texte: "@Curier Davy Merci beaucoup pour ton retour ! Ca me fait plaisir de te lire" },
      { nom: "François DAOUD", texte: "@Nathalie Rossa Tisseau Merci Nathalie !" },
      { nom: "François DAOUD", texte: "Merci @Mario Gaudreault" },
      { nom: "François DAOUD", texte: "@Sophie Boeuf Brunner Avec plaisir Sophie, je suis ravi que ce partage d’expérience t’inspire" },
      { nom: "François DAOUD", texte: "@Kylian Baude Merci ! Le Funnels Club est en train de changer ma vie, vraiment 🙏" },
      { nom: "François DAOUD", texte: "@Ilyasse Setti Merci infiniment Ilyasse," },
      { nom: "Bruno Beuret", texte: "@François DAOUD Oui moi aussi, merci pour tes encouragements , j’ai déjà des éléments en Bêta mais quand je vois tes résultats ! ça me motive de fini cette version bêta !" },
      { nom: "Mario Orsinet", texte: "@Ilyasse Setti Incroyable ! Bravo 🚀🚀🚀" },
      { nom: "Laurent et Élisabeth.", texte: "Merci @François DAOUD pour ce retour d’expérience c’est encourageant et bravo pour ton état d’esprit et  tes résultats !" },
      { nom: "Sacha COHEN", texte: "Félicitations @François DAOUD !🎉 Tu penses que cette explosion est dûe à quoi ? Que t’es bien meilleur en closing comparé au mois d’avant ? Ainsi que la période de vacances terminée ?" },
      { nom: "Khaled B.", texte: "Félicitations @François DAOUD  c’est vraiment très inspirant j’ai du mal à continuer à implémenter à cause du travail salarié à côté mais ça me motive encore plus ! Merci" },
      { nom: "Doan PANNIER", texte: "Merci pour ce témoignage très encourageant @François DAOUD ! De l’intérêt de garder le cap et de suivre les précieux conseils des coachs ! Excellente continuation et savoure ce succès !" },
      { nom: "Florence CHAGNEUX", texte: "Félicitations @François DAOUD !" },
      { nom: "Frédéric FELLER", texte: "Bravo, pour ta persévérance et ton initiative de consulter les coachs qui ont l'habitude de ces situations. C’est vraiment encourageant pour une personne comme moi, qui débute. Merci pour ce partage positif." },
      { nom: "Clemence Privé", texte: "Merci pr ton post @François DAOUD ça me prépare mentalement à ce qui m attend 🧘‍♀️ et bravo à toi d avoir tenu bon !" },
      { nom: "Dory Marciuk", texte: "Merci beaucoup pour ce partage très intéressant !" },
      { nom: "Sylvie PONT & Yannick DIAZ", texte: "Félicitations !!" },
      { nom: "Mayis Al Tatari", texte: "C’est très inspirant. Merci pour le partage !" },
      { nom: "Cathy Arnaud", texte: "chouette !! c’est tres encourageant …" },
      { nom: "Louise", texte: "Félicitations François , c’est inspirant !" },
      { nom: "Jérôme", texte: "Bravo @François DAOUD ! ça fait du bien de lire ça ! 💪💪" },
      { nom: "Merveille Lucia", texte: "wow , je suis contente de te lire ce matin et très heureuse pour toi . Félicitation 😀" },
      { nom: "Merveille Lucia", texte: "@Bruno Beuret 👍" },
      { nom: "sheikh ali", texte: "Magnifique bravo 🙌" },
      { nom: "HUGUENIN Benoit", texte: "Merci François pour ton partage qui tombe à pic ce matin, comme par hasard!!! belle continuation a toi et on lache rien ;)))" },
      { nom: "Amandine GUERREIRO", texte: "Incroyable performance ! Bravo et merci car ton témoignage nous encourage beaucoup !!" },
      { nom: "Laëtitia Miroux", texte: "Merci pour ton partage François, Bravo pour ce succés. Profite et capitalise !" },
      { nom: "C.O", texte: "Bravo !" },
      { nom: "François DAOUD", texte: "@Laurent et Élisabeth. Merci pour ton message ça fait plaisir de te (vous ?) lire ! Les résultats sont dingues et je les souhaite pour tous les membres, franchement y a pas de raison que ça ait marché pour moi, et pas pour les autres !" },
      { nom: "François DAOUD", texte: "@Sacha COHEN Hello Sacha, merci pour ton message 🙂 Je pense que y a une notion de période, mais également de compétence de closing. Et, même si ce n’est pas trop palpable dis comme ça, de capacité à tenir malgré les moments de down mental. J’étais à 2 doigts de faire n’importe quoi, et en en parlant aux coachs, ils m’ont rassuré et aidé à prendre de la hauteur. Tout cumulé, ça a généré cette grosse phrase de réussite !" },
      { nom: "François DAOUD", texte: "@Khaled B. Salut Khaled, mince je comprends que ce n’est pas facile de cumuler les 2. Il y a vraiment une notion de dépassement de soi provisoire (quelques mois). Une fois que la machine s’emballe, elle s’emballe vraiment, et quand tu récoltes les fruits de tes efforts, c’est un changement de vie radical. C’est ce qui m’est arrivé et c’est le bonheur. Courage, tu vas (et tu dois) y arriver toi aussi !" },
      { nom: "François DAOUD", texte: "@Doan PANNIER Merci Doan ! Ton message me fait très plaisir ! Beaucoup de réussite à toi aussi !" },
      { nom: "François DAOUD", texte: "@Florence CHAGNEUX Merci Florence !" },
      { nom: "François DAOUD", texte: "@Frédéric FELLER Bonjour Frédéric, et merci pour ce chaleureux message. Effectivement, ils ont su appuyer là où il faut pour m’aider à tenir le cap… Le jeu en vaut la chandelle, parce que là,  ça y est, la magie a pris ! Bon courage à toi aussi, et hâte que tu y arrives à ton tour !" },
      { nom: "François DAOUD", texte: "@Clemence Privé Merci pour ton message, yes ! Vraiment cette histoire d’émotions, il faut gérer ça, et être transparent avec les coachs et être réceptif à leur retours ! ca a été la clé pour moi !" },
      { nom: "François DAOUD", texte: "@Dory Marciuk Merci pour ton retour !" },
      { nom: "François DAOUD", texte: "@Sylvie PONT & Yannick DIAZ Merci !!!" },
      { nom: "François DAOUD", texte: "@Mayis Al Tatari Merci pour ton retour !" },
      { nom: "François DAOUD", texte: "@Cathy Arnaud C’est bientôt ton tour Cathy ! Et merci pour ton retour !" },
      { nom: "François DAOUD", texte: "@Louise Merci Louise !" },
      { nom: "François DAOUD", texte: "@Jérôme Yes Jérôme, on garde le cap, quand ça prend, ça prend ! Il faut continuer à optimiser jusqu’à ce moment 🦾" },
      { nom: "François DAOUD", texte: "@Merveille Lucia Merci ! Ca vaut le coup de garder le cap ! Quand ça décolle, ça décolle !" },
      { nom: "François DAOUD", texte: "@sheikh ali Merci !!!" },
      { nom: "François DAOUD", texte: "@HUGUENIN Benoit Merci pour ton retour Benoit ! Avec le recul, je constate que la principale difficulté me concernant a été la gestion des émotions (inquiétudes, peur que ça fonctionne pas, etc…). Meilleur remède : En parler aux coachs !" },
      { nom: "François DAOUD", texte: "@Ludivine Merci !!!" },
      { nom: "François DAOUD", texte: "@Amandine GUERREIRO Merci pour ton retour ! Je suis à peine plus loin que vous dans le parcours, ce sera bientôt votre tour 🙂" },
      { nom: "François DAOUD", texte: "@Laëtitia Miroux Merci pour ton retour ! Précieux conseils à appliquer ! Merci" },
      { nom: "François DAOUD", texte: "@C.O Merci!" },
      { nom: "Khaled B.", texte: "@François DAOUD à mon retour d’Asie je vais mettre les bouchées doubles merci ! 😊" },
      { nom: "Doan PANNIER", texte: "@François DAOUD 😉" },
    ],
  },
  {
    nom: "Judith Kamdem Simo",
    niche: null,
    portrait: null,
    titre: "Je ne savais pas encore que je serais la prochaine à écrire le mien.",
    surligne: ["j’ai quitté mon métier et mon gros salaire"],
    paragraphes: [
      "Quand j’ai découvert Funnels Club, je partais vraiment de zéro dans le digital.",
      "J’étais infirmière, je travaillais énormément, toujours des journées de 16 heures, souvent loin de ma famille. Financièrement, je gagnais très bien ma vie — plus de 8 000 $ nets certains mois — mais j’avais l’impression de ne pas avoir de vie. Je voyageais pour travailler, je laissais mes enfants, et au fond de moi je savais que je voulais construire autre chose.",
      "J’étais déjà dans le marketing de réseau, mais je ne savais pas comment vendre mes produits, comment trouver des clients autrement que par la prospection ou le démarchage, ni comment développer réellement mon activité en ligne.",
      "Puis je suis tombée sur une publicité de Rémy.",
      "Je me rappelle encore du déclic. Pendant mon closing, Maxime m’a fait comprendre qu’il était réellement possible de faire venir des clients à soi grâce au digital. Pour moi qui venais du monde traditionnel, ça a complètement changé ma vision.",
      "J’ai payé la formation cash. Je savais que c’était ce que je voulais.",
      "À ce moment-là, je n’avais pourtant pas beaucoup de temps. Quand je travaillais, j’enchaînais mes longues journées. Et pendant mes jours off, je travaillais sur ma formation du matin au soir. Je pouvais m’endormir devant à minuit et me relever à 3 h pour continuer.",
      "Je ratais parfois les coachings en direct, mais je ne ratais pratiquement aucune rediffusion. Je me souviens notamment des heures passées sur la route à écouter les replays de @Maxime LEGROS  sur le closing.",
      "Petit à petit, j’ai commencé à assembler les briques.",
      "J’ai appris à construire mes tunnels.",
      "J’ai appris à lancer mes campagnes publicitaires.",
      "J’ai appris à closer.",
      "J’ai créé mon offre à partir de rien.",
      "Et surtout, j’ai commencé à obtenir mes premiers résultats.",
      "Quand j’ai vu que ça fonctionnait alors que je n’y consacrais encore qu’une partie de mon temps, je me suis posé une question très simple :",
      "“Si ça fonctionne à 30 ou 40 %, qu’est-ce qui peut se passer si je m’y mets à 100 % ?”",
      "C’est là que j’ai pris une décision qui aurait été inimaginable pour moi auparavant : j’ai quitté mon métier et mon gros salaire pour me consacrer entièrement à ce que j’étais en train de construire.",
      "Tout n’a pas été facile. Il y a eu du stress, des périodes de doute, des choses à ajuster. Mais j’avais appris une phrase que je n’ai jamais oubliée :",
      "““Faire plus de ce qui marche et moins de ce qui ne marche pas””.",
      "Mes campagnes fonctionnaient, mais je savais qu’il me manquait encore quelque chose pour passer un cap.",
      "C’est là que @Geoffrey Bonniot  est intervenu.",
      "J’hésitais presque à demander autant d’aide, parce que je savais à quel point son temps était précieux. Mais il a accepté de travailler avec moi.",
      "Et là, les choses ont réellement accéléré.",
      "En seulement quelques mois, je suis passée d’environ 5 000 $ de chiffre à plus de 20 000 $, puis aujourd’hui, en plein mois d’août, je suis proche des 50 000 $.",
      "Et quand je regarde tout ça, ce qui me frappe le plus n’est même pas seulement le chiffre.",
      "C’est de me dire qu’une femme qui ne connaissait rien au digital, qui n’avait jamais construit de business en ligne, qui venait d’un métier totalement traditionnel, arrive aujourd’hui à mettre de la nourriture sur la table de sa famille grâce à ce qu’elle a appris à construire sur Internet.",
      "Je crois que ma plus grande leçon, c’est celle-ci :",
      "j’ai compris que je n’avais plus envie de perdre du temps à essayer de tout comprendre seule.",
      "Je préfère investir pour apprendre auprès de personnes qui ont déjà les résultats que je veux atteindre.",
      "Je paierais cher pour ne pas me tromper.",
      "Funnels Club m’a donné cette structure, cette vision et ces compétences que je n’avais pas.",
      "Alors merci @Rémy Jupille.",
      "Merci @Maxime LEGROS  pour toutes ces heures d’enseignement sur le closing.",
      "Et merci infiniment @Geoffrey Bonniot  pour l’accompagnement qui m’a permis de passer un nouveau cap.",
      "Quand je suis arrivée ici, je lisais les témoignages des autres en me demandant si un jour ce serait mon tour.",
      "Je ne savais pas encore que je serais la prochaine à écrire le mien.",
    ],
    reponses: [
      { nom: "Geoffrey Bonniot", texte: "Félicitations @Judith Kamdem Simo ! Tu peux être fier de ton parcours et du travail que tu as fourni. Tu mérites tes résultats et ce que tu vas pouvoir atteindre par la suite ! Merci pour ce partage ! 🚀" },
      { nom: "Judith Kamdem Simo", texte: "@Geoffrey Bonniot Ouiiii, encore merci infiniment !" },
      { nom: "Mauro Di Fino", texte: "Félicitations Judith!! Super témoignage." },
      { nom: "Ludivine", texte: "Bravo @Judith Kamdem Simo, ton parcours est une véritable inspiration pour tous les membres. Ce succès, tu ne le dois qu’à toi, félicitations à toi. Tu peux être fière de toi !" },
      { nom: "Guy Anastaze", texte: "Magnifique Judith ! Bravo pour ta belle réussite et Merci pour ton témoignage inspirant qui me donne de l’élan et du fuel 🔥🔥🔥" },
      { nom: "Brigitte Le Moine", texte: "Félicitations @Judith Kamdem Simo👏 , c’est un très bel exemple de réussite et ça me donne du courage pour m’y remettre après une pause de 6 mois." },
      { nom: "Judith Kamdem Simo", texte: "@Ludivine Merciii beaucoup !!!" },
      { nom: "Judith Kamdem Simo", texte: "@Mauro Di Fino merci beaucoup !" },
      { nom: "Judith Kamdem Simo", texte: "@Guy Anastaze Merci beaucoup" },
      { nom: "Judith Kamdem Simo", texte: "@Brigitte Le Moine Merci beaucoup, et ouii, fonce, Fonce ! Le meilleur moment pour t’y remettre était peut-être il y a six mois. Le deuxième meilleur moment, c’est maintenant. 💪🏽" },
      { nom: "Sophie Boeuf Brunner", texte: "Un grand merci pour ton témoignage Judith qui est super inspirant ! et un immense bravo pour ce que tu as accomplis !" },
      { nom: "Arnaud Perez", texte: "Bravo Judith, très inspirant et je crois que c’est ce que l’on veut tous ! Les membres de Funnels Club aussi d’ailleurs ☺️ En tous les cas ça donne envie de tout faire pour y arriver Bravo encore 👍" },
    ],
  },
  {
    nom: "Lilian Céré",
    niche: "Dirigeant d’une agence web spécialisé dans le BTP",
    portrait: "/immersion/communaute/lilian-cere.jpg",
    titre: "Je fais ce post pour ceux qui doutent.",
    surligne: ["j’ai réussi à en signer deux"],
    paragraphes: [
      "Je fais ce post pour ceux qui doutent.",
      "Cette semaine, j’ai closé deux clients. Et si je le partage, ce n’est pas pour me la raconter, mais pour être honnête sur le chemin.",
      "Ça fait longtemps que je travaille le closing. Et clairement, j’y ai pris quelques leçons de vie.",
      "Il y a deux semaines, j’avais un client hyper intéressant. Engagement en visio, échange fluide, tout était validé. Il ne manquait plus qu’une chose : qu’il rentre sa carte.",
      "On a repoussé le paiement à plus tard dans la journée. On n’était plus en visio. Et finalement… il n’a jamais payé.",
      "Sur le moment, j’ai même hésité à poster dans le groupe pour dire que j’avais signé. Et puis je me suis dit : attends qu’il paye. J’ai bien fait. Parce que ce client-là n’a jamais signé.",
      "Et ça m’a rappelé une chose essentielle : le closing, ce n’est pas facile.",
      "Mais quand le travail est fait sérieusement, quand on se fait accompagner, quand on analyse, qu’on corrige et qu’on continue… les choses finissent par s’aligner.",
      "Cette semaine, grâce au travail effectué et à l’accompagnement de Rémy et de toute l’équipe de Funnel Club, j’ai réussi à en signer deux.",
      "Ce que j’en retiens : le closing, ce n’est pas un talent. Ce n’est pas instantané. Et ce n’est clairement pas ce qu’on voit sur les réseaux.",
      "C’est de la progression, de l’entraînement, du volume. Faire des calls. Les réécouter. Analyser ceux qui n’ont pas marché… mais aussi ceux qui ont marché, pour se demander : comment j’aurais pu faire encore mieux ?",
      "C’est juste une question de temps.",
      "Aujourd’hui, je voulais surtout remercier toute l’équipe de Funnel Club ! Parce que je suis encore au début. Et justement… ce n’est que le début. Je compte bien continuer à progresser et tout arracher 🚀",
      "Et pour ceux qui doutent en ce moment, ou qui ont l’impression de stagner : ne perdez pas espoir. Le closing n’est pas une question de chance ni de talent inné. C’est une question de temps, de répétition et d’amélioration continue.",
      "Continuez à faire des calls. Continuez à les analyser. Continuez à progresser.",
      "Le reste finit toujours par suivre.",
    ],
    reponses: [
      { nom: "Barbara Bay", texte: "Tellement merci Lilian pour ton témoignage ! La tendance à l’auto-jugement à la dent dure, mais reproche-t-on à un petit enfant de tomber 100 fois avant de faire ses premiers pas ? C’est le lot de l’apprentissage que d’être coûteux. Il faut sans cesse remettre l’ouvrage sur le métier et recommencer jusqu’à ce que ce soit fluide. Je te rejoins quant à la qualité de l’accompagnement par l’équipe de Funnel’s et je me réjouis de faire bientôt mes premières expériences de closing. Belle journée à toi et surtout : BRAVO 👏🥳🤩" },
      { nom: "MADELEINE ROMMEL", texte: "Merci Lilian, même si j’en suis encore loin, en te lisant c’est tout à coup proche, possible, imminent ou en route, et la bonne énergie dégagée est le meilleur des “fuels” 😉" },
      { nom: "Many Soliman", texte: "Bravo a toi @Lilian Céré !!!🥳🥳" },
      { nom: "Mathieu Granchamp", texte: "Félicitations Lilian ! 🚀" },
      { nom: "Ludivine", texte: "Bravo @Lilian Céré, ton travail et ta remise en question paient ! Tu vas inspirer beaucoup de membres grâce à ton partage 🚀" },
      { nom: "Geoffrey Bonniot", texte: "Merci pour ton partage @Lilian Céré ! C’est mérité et cela va inspirer ! 🚀" },
      { nom: "Florence CHAGNEUX", texte: "👏👏👏👏👏" },
      { nom: "Clemence Privé", texte: "Salut @Lilian Céré ton post tombe à pic. Coup dur samedi de mon coté. R1 bien, bon profil. Vidéo de présentation vu plusieurs fois. Tjs ok pr R2 la veille. Et 30min avant… patatra “imprévu. Pas joignable avant vendredi.” Je m’étais préparé à être satisfaite quelque soit l’issue mais évidemment pas à ça. Mais bon une grande balade, on souffle et on repart comme tu dis. Allez bon lundi à tous 💪" },
      { nom: "Lilian Céré", texte: "@Clemence Privé salut Clémence, exactement ! C’est ce genre de petites expériences qui, justement, nous font grandir dans le business !" },
      { nom: "Olivier CAETANO", texte: "Merci @Lilian Céré pour ce témoignage inspirant !" },
      { nom: "Mauro Di Fino", texte: "Merci @Lilian Céré pour ce retour d’expérience. Tu n’es pas le seul à dire que le closing est tout un entraînement, et un apprentissage en le faisant. Bravo pour ces ventes! Il y en aura plein d’autres à venir !" },
      { nom: "Virak CHHUOR", texte: "Merci @Lilian Céré pour ton partage à la fois vulnérable et inspirante et ton message d’encouragement!!" },
      { nom: "Chrystel Gerard", texte: "Bravo @Lilian Céré et merci pour ce retour. D’autres sont à venir 😀" },
      { nom: "Maxime LEGROS", texte: "Félicitations @Lilian Céré 🚀🚀  Merci pour le partage, je pense que ça doit aider beaucoup de personnes et tu as tout à fait raison ! C'est une question de travail de persévérance Il y a des personnes qui sont plus à l'aise que d'autres mais d'autres personnes qui doivent beaucoup le travailler. Au bout du compte tout le monde peut y arriver car au delà du closing c'est une rencontre et c'est la validation d’un compatibilité entre êtres humains." },
      { nom: "Marjolaine Honor Luthier pour Violon, Alto et Violoncelle", texte: "Une victoire à célébrer! Excellent! 🤩🥳 On a tellement besoin de partage de la confrontation a la réalité et au moment clé où ça débloque!!!! Merci @Lilian Céré" },
      { nom: "Laëtitia Miroux", texte: "Bravo @Lilian Céré - c’est sur que le closing n’est pas une “science” simple à appliquer ! Il faut de la pugnacité et de l’envie d'e réussir …. merci pour ton partage !" },
      { nom: "Sandra H.", texte: "👏💪et merci pour le partage @Lilian Céré" },
      { nom: "Sacha COHEN", texte: "Clairement d’accord ! Félicitations 🥳" },
      { nom: "Mireille", texte: "Merci Lilian, ça me donne du courage!😉👍" },
      { nom: "Alexis Gaborit", texte: "Félicitiations @Lilian Céré 😃" },
      { nom: "Nelly frankenberg", texte: "Merci Lilian, ton témoignage est très aidant !!!! Merciiiiiii et felicitations !!!! lets’go !!!!!" },
    ],
  },
  {
    nom: "Guy Anastaze",
    niche: "Mentor de dirigeants",
    portrait: "/immersion/communaute/guy-anastaze.jpg",
    titre: "un mandat de 125´000 €",
    surligne: ["je n’aurai pas conçu mon offre comme je l’ai faite"],
    paragraphes: [
      "Bonjour à toutes et à tous,",
      "J’ai l’immense plaisir de vous informer qu’un de mes clients a beaucoup aimé le programme de ma formation en ligne que je lui ai présentée, et que je construis grâce à Funnels Club depuis plus d’un an. Il m’a demandé de m’en inspirer pour faire une formation en présentiel pour ses 6 membres du Codir et 6 membres des N—1. (10 jours répartis sur février, mars, avril, juin, septembre 2026).",
      "Résultat : un mandat de 125´000 € avec un acompte de 37’500 € payable maintenant.",
      "Sans Rémy, l’équipe, la communauté et la formation Funnels Club, je n’aurai pas conçu mon offre comme je l’ai faite, et je n’aurais pas eu ce mandat.",
      "Bien que différent de ce que je vise à terme avec ma formation en ligne, cela me montre que des opportunités diverses et fructueuses peuvent surgir grâce à Funnels Club.",
      "Cela me booste pour finir mes modules.",
      "Je suis infiniment reconnaissant à Rémy et à vous tous pour tout ce que vous m’apportez.",
      "Belle journée 🤗",
    ],
    reponses: [
      { nom: "Mohamed ASHAD", texte: "Bravo @Guy Anastaze  et Félicitations 🥳" },
      { nom: "Guy Anastaze", texte: "@Mohamed ASHAD 🙏" },
      { nom: "Christophe & Dominique Crapez", texte: "Congratulations Guy👋👋👋" },
      { nom: "Guy Anastaze", texte: "@Christophe & Dominique Crapez 🙏😉" },
      { nom: "Alizée et Yann", texte: "Magnifique Guy ! 🤩🔥 Très heureuse pour toi ! 🎉🥂🍾🙌🏻👏🏻💪🏻🏆 Merci de ton partage !" },
      { nom: "Judith Nah", texte: "Rohlalal félicitations à toi  Guy C est vraiment motivant de lire ça Juste waouhh 👌👌👌👌👌💪🏻💪🏻💪🏻💪🏻" },
      { nom: "Olivier CAETANO", texte: "Félicitations !" },
      { nom: "MADELEINE ROMMEL", texte: "c’est génial :) et super d’avoir présenté ta formation à un chef d’entreprise." },
      { nom: "Guy Anastaze", texte: "Merci @Olivier CAETANO" },
      { nom: "Guy Anastaze", texte: "@Judith Nah Ravi que cela te plaise 🤗🤗🤗" },
      { nom: "Guy Anastaze", texte: "Merci @Alizée et Yann pour votre chaleureux soutien 🤩🔥" },
      { nom: "Guy Anastaze", texte: "@MADELEINE ROMMEL Oui. J’ai ouvert une belle porte ! Et cette formation en présentiel m’aidera aussi pour ma formation en ligne. 🤩" },
      { nom: "Alexandra Sinkova", texte: "Wow Bravo! C’est inspirant 😃" },
      { nom: "Many Soliman", texte: "Un grand bravo a toi! Le debut de pleins de grandes choses! Je te souhaite le meilleur" },
      { nom: "Guy Anastaze", texte: "Merci @Many Soliman 😊" },
      { nom: "Guy Anastaze", texte: "Merci @Alexandra Sinkova 🤩" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations @Guy Anastaze ! 🚀" },
      { nom: "Laurent et Élisabeth.", texte: "Félicitations Guy !" },
      { nom: "Guy Anastaze", texte: "Merci @Geoffrey Bonniot 😊" },
      { nom: "Guy Anastaze", texte: "Merci @Laurent et Élisabeth.😊" },
      { nom: "Clemence Privé", texte: "Bravo @Guy Anastaze rien d’étonnant avec ton background ! félicitations" },
      { nom: "Guy Anastaze", texte: "Merci @Clemence Privé pour ton message très sympa. Je n’oublie pas de te feed-backer sur le DISC. J’ai été très pris ces derniers temps. Au plaisir de te retrouver lundi. 🤩" },
      { nom: "Marie Betty Vieux", texte: "Waw Good job, félicitations" },
      { nom: "Chrystel Gerard", texte: "Bravo, très contente pour toi. Champagne 😀🍾" },
      { nom: "Sarah de Azevedo", texte: "Merci Guy pour ce message, c’est très inspirant et encourageant. Et surtout bravo pour l’immense travail et le talent qu’il y a derrière tout cela." },
      { nom: "Guy Anastaze", texte: "@Sarah de Azevedo Merci Sarah pour ton retour qui me touche beaucoup. J’essaie le plus possible de faire un travail qui donne du sens à ce que je fais, me donne du plaisir et me fait sentir utile… Je te souhaite plein succès 🤗" },
      { nom: "Guy Anastaze", texte: "@Chrystel Gerard Merci Chrystel. Volontiers pour partager une coupe de Champagne. Comme disait Churchill, « en cas de victoire, je le mérite, en cas de défaite, j’en ai besoin ». 😜" },
      { nom: "Marjolaine Honor Luthier pour Violon, Alto et Violoncelle", texte: "Merci infiniment pour ce beau temoignage! ☺️🥰" },
      { nom: "Guy Anastaze", texte: "@Marjolaine Honor Luthier pour Violon, Alto et Violoncelle Merci Marjolaine. Je profite de ce moment pour te dire combien j’admire le métier de Luthier. Tu donne une âme à l’instrument et celle ci entrera en résonance avec celle du musicien qui saura la faire vibrer. Magnifique 😍" },
      { nom: "Barbara Bay", texte: "Les voies de la destinée sont impénétrables 😄 L’essentiel est de garder sa porte ouverte et son seuil propre pour accueillir les pépites du jour et celle-là, elle vaut son pesant d’or ! Tu vas pouvoir réinvestir tout cela dans tes cours en ligne comme tu le dis. Bravo et profite 🥳💗✨" },
      { nom: "Guy Anastaze", texte: "@Barbara Bay Merci Barbara, j’aime bien « les voies de la destinée sont impénétrables » tellement vraie ! Préparer les opportunités et rester à l’écoute … 🤩😘" },
      { nom: "Patrick Pinot", texte: "@Guy Anastaze, incroyable, Bravo 🙂" },
      { nom: "Guy Anastaze", texte: "@Patrick Pinot Merci Patrick. 🤩" },
      { nom: "Dominique BERTON & Michel ROUSSET", texte: "Bravo @Guy Anastaze 😊 Patience et persévérance…le tout bien accompagné" },
      { nom: "Guy Anastaze", texte: "@Dominique BERTON & Michel ROUSSET c’est tout à fait ça ! Merci à tous les deux 🤗" },
      { nom: "Barbara Bay", texte: "Mon chéri me répète toujours que la chance, c’est la préparation qui rencontre les opportunités ! 😃" },
      { nom: "Guy Anastaze", texte: "@Barbara Bay voici un post YT de Philippe Gabilliet que ton chéri appréciera probablement 😉 Tu me diras … https://youtu.be/OoF-_1YKjSU?si=HW-WgQuhXZdi-SsP" },
    ],
  },
  {
    nom: "Corentin Ghisalberti",
    niche: null,
    portrait: "/immersion/communaute/corentin-ghisalberti.jpg",
    titre: "ce n’est pas un sprint, c’est un marathon",
    surligne: ["celle de vivre une vie de liberté"],
    paragraphes: [
      "Salut à tous !",
      "J’espère que vous allez bien 😊",
      "Aujourd’hui, certains de mes clients m’ont remercié pour le travail que je faisais et pour tout ce que j’apportais à leur entreprise au quotidien et ça m’a vraiment fait chaud au cœur.",
      "Je me suis donc dit qu’il fallait aussi que je vous remercie, car je viens tout juste de réserver mon aller simple pour quitter la France. Après 5 ans de travail acharné, c’est un moment très symbolique pour moi.",
      "On a encore beaucoup de chemin à parcourir ensemble pour atteindre nos objectifs, mais j’ai compris une chose essentielle : ce n’est pas un sprint, c’est un marathon.",
      "Derrière nos écrans, on ne mesure pas toujours l’impact que nous avons sur la vie de nos clients, car tout cela reste souvent immatériel. Mais le rêve que je vais pouvoir réaliser cette année, c’est grâce à vous.",
      "J’aurai la chance de passer 4 mois en Asie, entre Bangkok et Kuala Lumpur, avant d’arriver à Abu Dhabi le 13 mars.",
      "Alors merci du fond du cœur à toute l’équipe du Funnel Club @Rémy Jupille @Geoffrey Bonniot et toutes les personnes qui travaillent à vos côtés, car sans vous, tout cela serait sûrement encore loin. Je vais enfin pouvoir honorer la promesse faite à ma femme il y a 5 ans : celle de vivre une vie de liberté.",
      "Merci aussi à @BUFFET Roland, pour ton soutien dans les moments plus difficiles. Je m’en souviendrai, et ma porte sera toujours grande ouverte pour toi — ainsi que pour tous les membres du Mastermind.",
      "(Heureux de vous accueillir si vous passez dans l’un de ces trois pays 🌏)",
      "Je ne suis pas très sentimental, donc je ne vais pas en dire plus, mais sachez que vous avez changé deux vies cette année : la mienne, celle de ma femme… et très bientôt, celles de mes futurs collaborateurs.",
      "🙏 Merci pour tout.",
    ],
    reponses: [
      { nom: "BUFFET Roland", texte: "Salut @Corentin Ghisalberti, Merci pour ce beau partage. C’est un message que je pourrais moi aussi écrire (avec moins de talent 😅) pour remercier @Rémy Jupille et toute son équipe ! Merci pour ta gentille attention et si ta porte m’est ouverte, sache que la mienne l’est aussi quand tu veux ! Je te souhaite donc beaucoup de bonheur avec ton épouse, beaucoup de réussite dans ton business et surtout de vivre pleinement tout ce que la vie va t’apporter ! Merci à toi et à bientôt en visio (et oui, je finis avec une superbe rime 🤣) La bise" },
      { nom: "François DAOUD", texte: "Ouaou Corentin… Je viens d'arriver au mastermind avec la volonté de changer ma vie. Je veux aller chercher cette liberté après 13 ans d'aventure entrepreneuriale compliquée. Et ce matin je me connecte comme un matin, puis je tombe sur ton message… En te lisant, j'ai senti une énorme joie pour toi : c'est beau, c'est inspirant. Tu l'as fait, et merci mille fois de le partager ! Ce que tu mentionnes est un objectif de vie tellement énorme et félicitations de t'être investi à ce point pour l'atteindre. Tout le monde n'en es pas capable, toi oui. Je suis admiratif ! Encore bravo et félicitations pour cet énorme accomplissement 💪🏼" },
      { nom: "Geoffrey Bonniot", texte: "Merci pour ton partage @Corentin Ghisalberti. Tu peux être fier de ce que tu as accompli ! Profite bien de ces nouvelles aventures ! 🚀 🛩️" },
      { nom: "Augustin Passy", texte: "C’est magnifique @Corentin Ghisalberti Félicitations, on est ensemble, profite tu vas vraiment t’amuser ! C’est possible qu’on soit dans le coin au même moment d’ailleurs je suis en Bangkok a partir du 8 janvier pour 1 mois 🚀" },
      { nom: "Corentin Ghisalberti", texte: "@Augustin Passy Merci beaucoup! Mais oui ça serait incroyable qu’on se voit à Bangkok, j’y serais du 21 Janvier au 13 Mars!" },
      { nom: "Corentin Ghisalberti", texte: "@Geoffrey Bonniot Merci beaucoup! 🙏🏻" },
      { nom: "Corentin Ghisalberti", texte: "@François DAOUD Merci pour ce jolie message François, vu ton démarrage j’ai aucun doute que tu y parviendras également!" },
      { nom: "Corentin Ghisalberti", texte: "@BUFFET Roland Merci pour ton message, si on continue à bosser chacun d’entre nous vivra dans un pays différent et ça nous fera des résidences secondaires de partout 😅" },
      { nom: "Rémy Jupille", texte: "Message vocal" },
      { nom: "Corentin Ghisalberti", texte: "@Rémy Jupille Merci beaucoup pour le message! Je t’avoue que pour le moment je vois ça plutôt comme un changement d’environnement qu’un voyage, justement je vais vouloir m’enfermer pour continuer à croitre le plus fort possible, l’expérience me détendra au fur et à mesure 😅 Top pour le déménagement, tu as succombé toi aussi à l’appel de Dubai 😅 Trop cool pour vous aussi ducoup et avec grand plaisir pour ce voir et on continue à travailler!" },
    ],
  },
  {
    nom: "Mathieu Granchamp",
    niche: null,
    portrait: "/immersion/communaute/mathieu-granchamp.jpg",
    titre: "j’ai officiellement closé ma première cliente",
    surligne: ["cette fameuse “deuxième source de revenus”"],
    paragraphes: [
      "Nous y voilà, hier soir, j’ai officiellement closé ma première cliente ! Quelle joie, quel bonheur !",
      "C’était d’ailleurs un jour symbolique pour plusieurs raisons, et notamment parce que ça faisait exactement 10 mois que j’ai commencé ce projet.",
      "J’ai commencé à bosser dessus dans l’ombre seul et sans stratégie le 9 février 2025 et moins d’un an plus tard, j’ai débloqué cette fameuse “deuxième source de revenus”. A savoir qu’en tant que kiné et ayant déjà beaucoup de charges, je réalise beaucoup de consultations par semaine (45h/semaine), donc tout mon temps libre est allouée à mes objectifs. (Sachant que je forme tous les mois, donc je n’ai même pas fait que FC)",
      "J’ai rejoint FC le 24 août mais j’avais déjà une bonne base (system.io, mon offre pratiquement bouclée, déjà essayé fb ads), cela m’a donné un coup d’accélérateur : 3 mois et demi plus tard, nous y voilà à la première vente.",
      "Un grand merci à tous les coaches et aux membres :",
      "@Rémy Jupille pour FC et la stratégie",
      "@Geoffrey Bonniot pour le dévouement (je me souviens notamment que tu as répondu à la refonte de mon copywriting à 15h un samedi donc si tu étais à Maurice, 19h ?)",
      "@Maxime LEGROS pour les rediff de coaching que j’écoute attentivement",
      "@François DAOUD qui m’a donné envie de commencer à écouter les rediff de closing quand il en avait partagé une ainsi que son témoignage en septembre",
      "@Nicolas Majois ❤️ @Many Soliman ❤️ @Clemence Privé @Olivier CAETANO @Marlyse et Richard de Villeneuve @Laurent et Élisabeth. pour les encouragements et le soutien !",
      "et finalement @Mattys Hamonic !",
      "IMG_4844.mov",
    ],
    reponses: [
      { nom: "Clemence Privé", texte: "Top bravo @Mathieu Granchamp ravie pour toi ! La première c est tout un symbole 👏" },
      { nom: "Colas Zibaut", texte: "Allez 🙌🏻" },
      { nom: "Olivier CAETANO", texte: "Super ! Félicitations ! Persévérance et organisation pour atteindre les objectifs. Merci pour ce partage et bon courage pour les prochaines 😊" },
      { nom: "Many Soliman", texte: "Après avoir recherché les mots qui devraient être écrit dans ce message. J’en ai conclu que rien ne vaut plus  qu’un « BRAVO » sincère. 🥳🥳🥳" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations pour ton travail @Mathieu Granchamp, cette première est logique et méritée ! 🚀" },
      { nom: "MADELEINE ROMMEL", texte: "Félicitations Mathieu Granchamp  - compatriote et collègue : c’est encourageant de te voir en haut, quand on campe en bas … très motivant et …à savourer :)" },
      { nom: "Mathieu Granchamp", texte: "Merci @MADELEINE ROMMEL ! Je suis encore loin du sommet et c’est normal que ça prenne du temps, j’ai commencé à travailler là-dessus il y a 10 mois déjà. 10 mois sans résultat. Sois patiente et persévérante, c’est la clé 😊" },
      { nom: "Maxime LEGROS", texte: "Bravo @Mathieu Granchamp 🔥🔥 LA 1ère vente fait toujours du bien ça débloque (vraiment) quelque chose ! Je suis très content pour toi tu le mérites, et j’espère que c’est le début d’une belle série 🚀🚀" },
      { nom: "Nathalie Rossa Tisseau", texte: "Félicitations @Mathieu Granchamp !! 🥳La 1ère vente d’une longue série ! … Et c’est très motivant pour nous aussi ! 🤩" },
      { nom: "BEATRICE MARTIN", texte: "Super Mathieu et bravo pour ta persévérance !!! Merci pour ce partage qui nous motive🙏 belle réussite à toi !" },
      { nom: "Chrystel Gerard", texte: "Bravo @Mathieu Granchamp" },
      { nom: "Mathieu Granchamp", texte: "Deuxième client aujourd’hui : R1 à 11h R2 à 18h et signature du contrat + onboarding direct Je vous dis ça pour vous encourager les gars ! Le prochain, c’est pour vous ! 🔥" },
      { nom: "Rémy Jupille", texte: "@Mathieu Granchamp ça commence ! 🥂" },
      { nom: "François DAOUD", texte: "Hello Mathieu ! Ouaou un IMMENSE bravo pour cet accomplissement ! Ca y est, la machine démarre “sérieusement” 😉 Bravo pour cette résilience, ça ne peut évoluer que dans un sens ! On continue, on optimise, et on continue 🚀🚀🚀" },
      { nom: "Mathieu Granchamp", texte: "Merci @Rémy Jupille ! ❤️ (mp)" },
      { nom: "Geoffrey Bonniot", texte: "@Mathieu Granchamp Let’s go, félicitations ! 🚀" },
      { nom: "Nelly frankenberg", texte: "Bravo et felicitations @Mathieu Granchamp !!!!!🥳🥂" },
    ],
  },
  {
    nom: "Laëtitia Miroux",
    niche: "Fondatrice Exportateurs Engagés - Méthode structurée, résultats export concrets",
    portrait: "/immersion/communaute/laetitia-miroux.jpg",
    titre: "Ce n’est plus une idée. Ce n’est plus un projet. C’est concret.",
    surligne: ["1h03 de coaching"],
    paragraphes: [
      "@Rémy Jupille - @Geoffrey Bonniot - @Maxime LEGROS - bonsoir à toutes et tous",
      "Ce matin, j’ai donné mon tout premier coaching de groupe dans ma communauté “Les Exportateurs Engagés”.",
      "On est 4 personnes dont 3 membres ! Donc oui, c’est un petit début. Mais c’est un début réel. Et honnêtement, avant de commencer… j’avais les “boules”.",
      "Peur qu’il n’y ait rien à dire. Peur que ce soit vide. Peur que les membres ne parlent pas. Peur de ne pas savoir comment prendre le coaching en main.",
      "C’était mon premier.",
      "Finalement, j’ai structuré la session en trois temps :",
      "Présentation de chacun : pourquoi ils ont rejoint les Exportateurs Engagés et quelles sont leurs problématiques.",
      "Leurs retours sur leurs premières utilisations de mon espace membre.",
      "Leurs questions concrètes sur leurs problématiques actuelles.",
      "Résultat ? 1h03 de coaching et j’ai dû arrêter pour respecter le cadre d’une heure 😃.",
      "Les échanges étaient riches. Il y a eu beaucoup de questions. Les membres ont contribué aux réflexions des autres. On a même défini de futurs sujets que je vais intégrer dans mon espace membre. Et ça, c’est précieux💎.",
      "Je suis encore en offre bêta. Une partie est construite, mais pas tout. Donc leurs retours vont me permettre d’améliorer la plateforme, d’enrichir les contenus et d’ajuster l’offre au plus proche de leurs besoins réels.",
      "Ce matin, j’ai vraiment ressenti ce que ça veut dire : faire vivre un espace membre (même si ce n’est qu’un début). Ce n’est plus une idée. Ce n’est plus un projet. C’est concret. 😱",
      "Je suis très contente aussi de l’état d’esprit des trois premiers membres. Positifs, impliqués, avec une vraie envie d’avancer et de réussir leur projet d’exportation. Je suis donc RAVIE de la sélection de mes membres! Il y avait une vraie bonne ambiance, presque un mini-salon tellement nous étions peu nombreux.",
      "Et je sais que ma façon d’animer va évoluer avec le temps. Comme tout, ça s’apprend, ça se peaufine, ça se structure.",
      "Mais aujourd’hui, c’est une victoire. Une petite victoire peut-être en chiffres. Mais une grande victoire intérieure.",
      "Je souhaite à tous celles et ceux qui sont en train de construire leur offre de vivre ce moment-là. Et je me souhaite à moi-même de continuer, de recruter de nouveaux membres (intéressants, positifs, motivés et percutants) et de faire grandir cette communauté 😌.",
      "J’avance et ça fait plaisir à vivre.",
      "Merci Funnels Club pour le cadre et la méthode 😍.",
    ],
    reponses: [
      { nom: "BEATRICE MARTIN", texte: "Magnifique témoignage et très bien exprimé ! Merci beaucoup et je te souhaite une très belle continuation sur cette lancée !" },
      { nom: "Ludivine", texte: "Bravo @Laëtitia Miroux de plus,c’est toujours très gratifiant de voir son projet se concrétiser. Tu peux être fière de toi !" },
      { nom: "Olivier CAETANO", texte: "Merci pour ce témoignage motivant et félicitations !" },
      { nom: "Laëtitia Miroux", texte: "@Ludivine Merci Ludivine ! Tes mots sont sympas et très juste !" },
      { nom: "Laëtitia Miroux", texte: "@Olivier CAETANO Merci Olivier !" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations @Laëtitia Miroux ! 🚀" },
      { nom: "Aude et Anaïs Bonroy-Riotte", texte: "Bravo et merci pour ce partage, c'est encourageant." },
    ],
  },
  {
    nom: "Linn",
    niche: "Styliste et  Conseillère en image",
    portrait: "/immersion/communaute/linn.jpg",
    titre: "l’un des meilleurs espaces de formation dans lequel j’ai été",
    surligne: ["2025 = maturation"],
    paragraphes: [
      "Hello à tous et très bonne année !",
      "Je me réveille un peu tard pour un message collectif (on est déjà mi-janvier 😅) mais je tenais vraiment à vous la souhaiter.",
      "Un petit mot aussi pour remercier les coachs : @Rémy Jupille, @Geoffrey Bonniot, @Maxime LEGROS, @Ludivine et  @Kylian Baude  qui m’a closé il y a déjà un moment, même si de base je n’avais pas prévu de commencer tout de suite ( trop de travail avant de vendre) au final c’était une très bonne décision 😄 merci à toi.",
      "Le Funnel Club a vraiment compté dans mon année 2025, même si je ne suis pas très “communauté” de base 😅 team introverti 🤭",
      "J’ai appris beaucoup de choses  sur le business mais aussi sur moi, sur la manière de construire une offre, de structurer un produit, etc.",
      "Je n’ai pas été très active dans les coachings cette année, parce que j’ai passé beaucoup de temps en construction :",
      "– structuration de mon offre",
      "– création d’un book de plus de 100 pages",
      "– 60+ petites vidéos pour mes clientes et mon espace",
      "– définition de ma cible 🎯",
      "– tunnel, hébergement, et début de ma chaîne YouTube",
      "– relance de mon Instagram",
      "Donc 2025 = maturation",
      "2026 = expansion ✨",
      "Pour 2026, objectif : premiers clients et beaucoup d’organique au premier trimestre, puis pub + closing une fois que la machine tourne avant 2027, je l’espère.",
      "J’ai beaucoup écouté les coachings cette année, j’ai l’impression de connaître @Virak CHHUOR, @Sacha COHEN et @Jérôme et @François DAOUD alors qu’on ne s’est jamais parlé 😂 (et @Tatiana Moreau + @Clemence Privé  aussi !)",
      "Merci pour votre bienveillance et votre guidance.",
      "C’est sincèrement l’un des meilleurs espaces de formation dans lequel j’ai été. I swear 🫶🏻",
      "Je vous souhaite une très belle année 2026, pleine  de réussite pro et perso 😄",
      "Au plaisir de vous retrouver dans d’autres contextes cette année ! pleutre dans 2 ou 3 mois , je ne sais pas",
      "Linn",
    ],
    reponses: [
      { nom: "Clemence Privé", texte: "Merci @Linn 🦋 très touchée d’être citée. La visioconférence et le digital/technique (via l event) est une habitude de boulot pr moi. De mon côté, je suis impressionnée par ceux qui comme toi font de l’organique poussée. On a chacun ses montagnes ! Mais je te rejoins même si j espérai au moins une vente avant la fin, j ai également bcp appris ici aussi, et de belles “rencontres”. Aucun regret. Belle année à toi aussi !" },
      { nom: "MADELEINE ROMMEL", texte: "Merci pour ton beau partage, Linn, c’est porteur et encourageant ;) suis impressionnée par tout ce que tu as déjà accompli. Contente qu’on soit “dans le même bateau”. Que 2026 soit riche en réalisations pour chacun d’entre nous y compris toute l’équipe !!" },
      { nom: "Linn 🦋", texte: "@Clemence Privé Merci Clémence 😉 Franchement, je suis impressionnée aussi par ton parcours. Mener un projet en parallèle du boulot, avec un bébé et tout ce que ça implique, c’est une autre montagne. De mon côté j’ai un contexte beaucoup plus favorable , et j’ai aussi l’avantage d’être très “créa - organique”, donc c’est plus naturel pour moi d’aller vers ce type de construction. En tout cas j’espère que 2026 te donnera ta première vente (et plein d’autres derrière 🫶🏻)." },
      { nom: "Linn 🦋", texte: "@MADELEINE ROMMEL Merci Madeleine, c’est très gentil à toi. Et oui on est dans le même bateau. ⛵️ Je suis au admirative de ton parcours, dans ta bio. Tu dois être multi et touche à tout comme moi. Bon courage ✨ et à bientôt ✌️" },
      { nom: "Sacha COHEN", texte: "Pleins de succès pour cette année @Linn 🦋 et également une bonne année ! 🥳" },
      { nom: "Ludivine", texte: "Très belle année à toi @Linn 🦋, que cette année 2026 soit la tienne 💪✨ et celle de tous les funneliens 🚀" },
      { nom: "Clemence Privé", texte: "@Linn 🦋 Tes bons voeux m’ont porté chance. Je viens d’avoir un inscrit avec résa d’appel pr samedi dans la foulée. Profil pile dans ma cible d’ap le formulaire Calendly : “salarié en charge d’events niveau débutant”. Allez fingers crossed !" },
      { nom: "Linn 🦋", texte: "@Clemence Privé top 👍🏻 je suis trop contente pour toi 🫶🏻" },
      { nom: "François DAOUD", texte: "Hello Linn, Je suis ravi de te lire et je te souhaite tout plein de réussite pour cette nouvelle année ! Tu es entre de bonnes mains. Ton objectif du premier trimestre 2026 est un très bel objectif : Tu boostes l’acquisition et tu commences tranquillement à remplir ton pipeline. Allez, à toi de jouer, ça ne peut que aller dans un sens ✨ Bonne continuation et à bientôt !" },
      { nom: "Linn 🦋", texte: "@François DAOUD merci bcp ce que tu as accompli est mon goal . Je pense que ça ira ! Je l’espère ✨ bon courage pour la suite ." },
      { nom: "Geoffrey Bonniot", texte: "Merci pour ton mot @Linn 🦋 ! Tu peux être fière de toi et de ton avancé ! 🚀 Très belle année 2026 ! 🍾" },
      { nom: "Virak CHHUOR", texte: "Merci @Linn 🦋 pour tous tes partages et oui faisons de cette année 2026 une réussite orchestrale pour nous tous et les valeurs que nous servons dans nos accompagnements !! Le monde est un vrai orchestre où chaque a sa place et son rôle à contribuer!" },
    ],
  },
  {
    nom: "Cédric Bizet",
    niche: "J'aide les entrepreneurs à se digitaliser.",
    portrait: "/immersion/communaute/cedric-bizet.jpg",
    titre: "je partais de rien, 0 connaissance",
    surligne: ["maintenant je gagne plusieurs milliers d’euros"],
    paragraphes: [
      "Bonjour à toutes et à tous,",
      "Ravi de découvrir cette nouvelle version après quelques mois d’absence..",
      "Je tiens avant tout à vous remercier vous, la superbe équipe de Rémy, c’est vrai qu’on a tendance à l’oublier et à rester la tête dans notre business, notre projet, égoïstement. Mais il faut le souligné vous êtes comme nos grand frères / nos grandes sœur, toujours là pour nous booster quand on a un coup de mou et surtout là pour nous tirer vers le haut dans les moments compliqués. On peut compter sur vous et tout le monde c’est à quel point c’est important.",
      "J’ai lu ta lettre Rémy, et j’ai directement compris de quoi tu parlais, et j’espère que tout le monde réalise à quel point on est bien tombé ici à Funnels club, vous avez un coeur en or et vous mérité qu’on vous le dise plus souvent, MERCI ! J’espère avec ce message vous effacez un peu de cette frustration qui peut venir par moment.. C’est pas toujours évident même pour vous :)",
      "En tout cas, soyez en sur vous faites de l’excellent boulot, c’est grâce à funnels club que j’ai débuté le business, je partais de rien, 0 connaissance, et maintenant je gagne plusieurs milliers d’euros et vous n’y êtes pas pour rien !",
      "Funnels club évolue et à chaque fois de mieux en mieux, hâte de découvrir ces nouvelles vidéos d’état d’esprit.",
      "Et pour les nouveaux membres sachez que funnels club c’est bien plus qu’une communauté, c’est une famille, certes ça a un coût mais les personnes ici sont toutes prêtes à vous aider et à vous propulser vers la réussite, en tout cas si vous avez des questions ou quoique ce soit je serais ravi de vous aider à mon échelle !",
    ],
    reponses: [
      { nom: "Mbemba", texte: "Très beau témoignage ! Je partage la même chose" },
      { nom: "Geoffrey Bonniot", texte: "Merci pour ton message @Cédric Bizet ! 🚀" },
    ],
  },
  {
    nom: "Sacha Cohen",
    niche: "Nettoyage Boost System",
    portrait: "/immersion/communaute/sacha-cohen.jpg",
    titre: "4h après mon post j’ai ma première vraie vente",
    surligne: ["17 réservations rien que pour la 1ère semaine du mois"],
    paragraphes: [
      "Petit post pour donner quelques chiffres. Depuis début août :",
      "17 réservations rien que pour la 1ère semaine du mois (planning full 😬)",
      "j’ai pour le moment fait 2 stratégies",
      "2 ventes… enfin pas vraiment, des dépôts de 50€ 😅😅",
      "Je suis content et frustré en même temps haha…",
      "Je ne sais pas vraiment si les dépôts vont tenir vers la vente finale ou être remboursés mais ça fait plaisir, c’est encourageant.",
      "Après avoir fait des dizaines et dizaines de call sur tout juillet, je sens que je prends les appels (et les objections) autrement, j’ai la sensation de mieux connaître, affiner ce que j’ai dis (ce qui est normal).",
      "Voilà maintenant je me demande comment ça va se passer pour remplir les 10 places de mes membres fondateurs pour l’offre bêta (sans parler de l’offre finale 🙏🏼) mais en tout cas j’ai l’impression d’avoir débloqué quelque chose de nouveau…",
      "À suivre 🙂",
      "EDIT : 4h après mon post j’ai ma première vraie vente 🥹",
      "Une prospect avec qui j’avais fais 2 RDV en juillet (et qui n’avait à ce moment même pas la possibilité de faire un dépôt de 50€) est revenue vers moi, prête à passer à la suite et qui s’est conclue en première vente avec un paiement en 3 fois 🫣",
    ],
    reponses: [
      { nom: "Rémy Jupille", texte: "Bravo ! Tu es entrain d’apprendre une compétence qui te servira pour toujours, ce n’est pas facile mais lorsque tu sera devenu très bon dans tes appels, tout va s’accélérer beaucoup plus vite que tu n’imagines 💪" },
      { nom: "Sacha COHEN", texte: "@Rémy Jupille j’ai hâte 🙏🏼 4h après ce post j’ai fais ma première vente 🫣 J’ai edit le post." },
      { nom: "Rémy Jupille", texte: "@Sacha COHEN c’est parti ! 💪" },
      { nom: "Kylian Baude", texte: "Bravo @Sacha COHEN ! 🚀" },
      { nom: "Sacha COHEN", texte: "Merci @Kylian Baude 😉" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations @Sacha COHEN ! 🚀" },
    ],
  },
  {
    nom: "Laëtitia Miroux",
    niche: "Fondatrice Exportateurs Engagés - Méthode structurée, résultats export concrets",
    portrait: "/immersion/communaute/laetitia-miroux.jpg",
    titre: "une mission à 15 000 dollars",
    surligne: ["j'ai signé mon premier membre au nouveau tarif"],
    paragraphes: [
      "@Geoffrey Bonniot @Rémy Jupille @Ludivine",
      "J'avais envie de partager une petite victoire avec vous.",
      "J'ai lancé une version non finie des Exportateurs Engagés en janvier. J'ai eu mes premiers membres à partir de fin mars à un tarif imbattable. Ils étaient trois. Ensuite, j'ai volontairement ralenti pour construire les fondations : travailler ma publicité, mon tunnel de vente et appliquer la méthode de Funnels Club étape par étape.",
      "Début juillet, j'ai signé mon premier membre au nouveau tarif grâce au processus de closing (2500 euro - tarif qui évoluera encore).",
      "Et aujourd'hui, une nouvelle étape vient d'être franchie.",
      "J'ai présenté ma méthode à un distributeur de produits canadiens qui souhaite se développer au Brésil. Au départ, je pensais lui vendre le programme. Finalement, il m'a expliqué qu'il ne souhaitait pas former quelqu'un en interne, mais qu'il voulait que j'applique directement ma méthode pour son entreprise.",
      "Résultat : nous sommes partis sur une mission à 15 000 dollars (hors commission) pour mettre en place la méthode Exportateurs Engagés sur le marché brésilien.",
      "Je suis vraiment heureuse, parce que ça confirme plusieurs choses.",
      "D'abord, avoir fait confiance à ma méthode et avoir suivi les conseils de Funnels Club m'a permis de construire une offre qui répond à un vrai besoin.",
      "Ensuite, ce projet va me permettre d'obtenir un cas concret, récent et très solide. Je suis convaincue qu'il deviendra un excellent support de communication pour faire rayonner Exportateurs Engagés.",
      "En parallèle, mon nouveau membre avance bien dans le programme, et grâce à la publicité, je reçois de plus en plus d'appels. Je sens que la machine est en train de se mettre en route.",
      "Les résultats ne sont pas arrivés du jour au lendemain. Ils se sont construits progressivement, avec des confirmations qui sont tombées sur plusieurs semaines. Mais aujourd'hui, je vois que le travail de fond finit par payer.",
      "Merci beaucoup à @Geoffrey Bonniot et à toute la communauté pour les conseils et les échanges. Ça motive à continuer.",
    ],
    reponses: [
      { nom: "Ludivine", texte: "Bravo @Laëtitia Miroux, tu peux être fière de toi ! Que des belles nouvelles 🚀" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations @Laëtitia Miroux ! 🚀" },
      { nom: "Béatrice Leroy", texte: "Bravo c’est encourageant pour nous qui débutons la formation :)" },
    ],
  },
  {
    nom: "Christophe et Dominique Crapez",
    niche: "High Impact Mindset",
    portrait: "/immersion/communaute/christophe-dominique-crapez.jpg",
    titre: "Rejoindre Funnels Club a été la meilleure décision professionnelle de ma vie !",
    surligne: ["notre projet prend enfin forme"],
    paragraphes: [
      "Coucou l’équipe,",
      "Je découvre la nouvelle version de Funnels Club et je la trouve incroyable ! Je suis ravie de faire partie de cette aventure, car je sais à quel point il est extraordinaire de partager son savoir avec les autres, et vous le faites à merveille. Rejoindre Funnels Club a été la meilleure décision professionnelle de ma vie !",
      "Sachez aussi que je ne me suis pas éclipsée pour abandonner. Après la réalisation de mon webinar, j’ai enchaîné directement sur la création de mon programme et je viens tout juste de terminer les vidéos aujourd’hui. Christophe gère maintenant la logistique, ce qui nous permettra de nous lancer dans le courant de la semaine prochaine. Nous aurons donc le plaisir de vous retrouver très bientôt pour la pub et le closing !",
      "Merci infiniment pour votre bienveillance et votre patience. Même si, au fond, aucun mot ne suffira jamais à vous remercier, Christophe et moi vous sommes profondément reconnaissants. Grâce à vous, notre projet prend enfin forme. MERCI!",
      "Dom et Chris",
    ],
    reponses: [

    ],
  },
  {
    nom: "Mario Orsinet",
    niche: "Musicien/Professeur de musique",
    portrait: "/immersion/communaute/mario-orsinet.jpg",
    titre: "je viens d’encaisser ce matin un premier paiement pour mon offre Bêta",
    surligne: ["Les efforts investis finissent toujours par payer"],
    paragraphes: [
      "Salut à tous!",
      "📢 Je suis très heureux de vous annoncer que je viens d’encaisser ce matin un premier paiement pour mon offre Bêta.😁",
      "C’est un acompte de 100€ pour une offre à 300€. C’est pas énorme mais ce n’est que le début 🚀 et c’est très encourageant pour la suite.",
      "J’en profite pour dire un GRAND MERCI 🙏🙏🙏 à @Rémy Jupille @Geoffrey Bonniot et à tous les coachs pour les conseils et le soutien.",
      "Je continue d’avancer et courage 💪 à ceux qui démarre avec Funnel Club. Les efforts investis finissent toujours par payer !!!",
    ],
    reponses: [
      { nom: "Ludivine", texte: "Bravo @Mario Orsinet, tu peux être fier de toi ! C’est uniquement grâce à ton assiduité après ton retour dans le Funnels Club 🚀 C’est que le début !" },
      { nom: "Mathieu Granchamp", texte: "Yeah ! Félicitations Mario ! C’est encourageant, bonne chance pour la suite ! 🎊" },
      { nom: "Mauro Di Fino", texte: "Félicitations Mario!!  C’est une première vente et j’espère que ce sera la première d’une longue série par la suite 🙂" },
      { nom: "Olivier CAETANO", texte: "Félicitations" },
      { nom: "Mario Orsinet", texte: "@Olivier CAETANO Merci 🙏" },
      { nom: "Mario Orsinet", texte: "@Mathieu Granchamp Merci tes encouragements🙏" },
      { nom: "Mario Orsinet", texte: "@Ludivine Merci beaucoup 🙏🙏" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations @Mario Orsinet pour ton premier encaissement ! Ce n’est que le début ! 🚀" },
      { nom: "Mario Orsinet", texte: "@Geoffrey Bonniot Merci 🙏" },
      { nom: "Nathalie Rossa Tisseau", texte: "Félicitations Mario !!!🤩" },
      { nom: "Mario Orsinet", texte: "@Nathalie Rossa Tisseau Merci 😁" },
      { nom: "Louise", texte: "Félicitations !" },
      { nom: "Alizée et Yann", texte: "Félicitations Mario !! 🥳" },
      { nom: "Mario Orsinet", texte: "@Alizée et Yann Merci à tous les deux !!" },
      { nom: "Mario Orsinet", texte: "@Louise Merci !" },
      { nom: "Chrystel Gerard", texte: "Félicitations !" },
      { nom: "Dory Marciuk", texte: "Bravo 🙏" },
      { nom: "Mario Orsinet", texte: "@Chrystel Gerard Merci !!!" },
      { nom: "Mario Orsinet", texte: "@Dory Marciuk Merci beaucoup !" },
    ],
  },
  {
    nom: "Nicolas Majois",
    niche: "Arrêter de boire c'est facile 👌",
    portrait: "/immersion/communaute/nicolas-majois.jpg",
    titre: "Voilà c’est fait",
    surligne: ["Et voilà vendredi un call, aujourd’hui première vente"],
    paragraphes: [
      "🎉🎉Voilà c’est fait🎉🎉 La machine est lancée 💪",
      "C’était pas facile, J’ai lancé mes pubs il y a un mois, et au bout de 15 jours elles avaient planté.",
      "Une semaine sans pub avant de dupliquer la campagne et de recommencer la phase d’apprentissage.",
      "Pas les mêmes pubs misent en avant et de moins bons résultats. Ma banque qui bloque facebook en tant que bénéficiaire douteux … indéblocable qu’ils disent … Mais j’me suis pas décourager, que du contraire enfait. Et voilà vendredi un call, aujourd’hui première vente 😄 J’suis trop content haha.",
    ],
    reponses: [
      { nom: "Rémy Jupille", texte: "Félicitations @Nicolas Majois ! Le premier d’une série ! 🥳" },
      { nom: "Mayis Al Tatari", texte: "Bravo ! Et merci pour le partage 👏" },
      { nom: "Mbemba", texte: "Félicitation !" },
      { nom: "Laëtitia Miroux", texte: "Bravo @Nicolas Majois - s’accroché et y croire c’est une bonne formule de réussite !" },
      { nom: "Nicolas Majois", texte: "@Laëtitia Miroux Merci beaucoup 😄" },
      { nom: "Nicolas Majois", texte: "@Mbemba Merci 😊" },
      { nom: "Nicolas Majois", texte: "@Mayis Al Tatari Merci 🙂 Et de rien, avec plaisir 😄" },
      { nom: "Nicolas Majois", texte: "@Rémy Jupille Merci beaucoup 😄 Oui c’est parti 💪" },
      { nom: "Sahra et Sofiane", texte: "Bravo ! La persévérance paie ! Je te souhaite encore plein de calls et de ventes !" },
      { nom: "Nicolas Majois", texte: "@Sahra et Sofiane Yes, merci beaucoup 🙂" },
      { nom: "Clemence Privé", texte: "Top Nicolas ! Bravo pr ta ténacité" },
      { nom: "Nicolas Majois", texte: "@Clemence Privé 😊 merci beaucoup" },
      { nom: "Kylian Baude", texte: "Bravo @Nicolas Majois !! J’étais convaincu que tu allais y arriver 💪💪🚀" },
      { nom: "Nicolas Majois", texte: "@Kylian Baude haha tu avais donc vu juste 😁 et c'est que le début 💪" },
      { nom: "Maxime LEGROS", texte: "Bravo @Nicolas Majois 🔥🔥 c’est que le début !!" },
      { nom: "Ludivine", texte: "La définition de la résilience ! bravo de t’être accroché @Nicolas Majois Tu peux être fier de toi 👏 et félicitations aussi pour ces premiers résultats, comme on dit : ce n’est que le début 🚀" },
      { nom: "Geoffrey Bonniot", texte: "Let’s go ! Félicitations pour ta première vente @Nicolas Majois ! 🚀" },
      { nom: "Nicolas Majois", texte: "@Geoffrey Bonniot merciii 🙂" },
      { nom: "Nicolas Majois", texte: "@Ludivine yes, merci beaucoup 😄" },
      { nom: "Nicolas Majois", texte: "@Maxime LEGROS oui 💪 merci 🙂" },
      { nom: "Olivier CAETANO", texte: "Félicitations !" },
      { nom: "Nicolas Majois", texte: "@Olivier CAETANO Merci 🙂" },
    ],
  },
  {
    nom: "Many Soliman",
    niche: null,
    portrait: "/immersion/communaute/many-soliman.jpg",
    titre: "j’ai réalisé mes 2 premiers closings pour ma bêta",
    surligne: ["Ces deux ventes sont le fruit de beaucoup de travail"],
    paragraphes: [
      "🔥 Petite update du jour !",
      "Aujourd’hui, j’ai réalisé mes 2 premiers closings pour ma bêta :  un premier à 1000 € et  un second à 1500 €",
      "Deux personnes super motivées et totalement partantes pour démarrer la formation avec moi dès lundi.",
      "Pour le moment, j’ai reçu de chaque côté un acompte de 250 €, le temps qu’ils s’organisent financièrement :",
      "paiement en 2 fois pour l’un Et un paiement en 3 fois pour l’autre.",
      "Petite info aussi : le dernier prospect lors de la panne m’a finalement ghosté, plus de nouvelles depuis.",
      "en tout cas je suis hyper content. Ces deux ventes sont le fruit de beaucoup de travail. Je sais que j’ai encore beaucoup à apprendre mais c’est un premier checkpoint important pour mon projet.",
      "Un merci particulier pour @Geoffrey Bonniot et @Kylian Baude qui on été jusque la ,mes interlocuteurs.",
    ],
    reponses: [
      { nom: "Frédéric FELLER", texte: "Bonjour Many, Je tenais à te féliciter pour ces 2 closing. C’est super encourageant pour la suite. Bonne journée. Frédéric" },
      { nom: "Kylian Baude", texte: "Félicitations @Many Soliman, c’est plus que mérité !! Trop content pour toi 🚀🚀🚀🚀🚀" },
      { nom: "Ludivine", texte: "Bravo Many, c’est que le début 💪" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations pour tes deux premiers closes, ce n’est que le début ! C’est mérité ! 🚀" },
      { nom: "Many Soliman", texte: "@Geoffrey Bonniot merciii" },
      { nom: "Many Soliman", texte: "@Frédéric FELLER merci pour tes encouragements. Je te souhaites plein de ventes!!!" },
      { nom: "Many Soliman", texte: "Mercii @Kylian Baude . Il reste encore beaucoup de chemin. J’en suis conscient" },
      { nom: "Many Soliman", texte: "@Ludivine ☺️☺️☺️" },
      { nom: "Marjolaine Honor Luthier pour Violon, Alto et Violoncelle", texte: "Wow! J'ai le goût de célébrer avec toi! 🎊✨️🎊 Hâte de faire aussi mes premiers pas avec Funnels! Ton post me témoigne que c'est possible! Merci de partager! ✨️😍" },
      { nom: "Frédéric FELLER", texte: "Merci beaucoup." },
      { nom: "Many Soliman", texte: "@Marjolaine Honor Luthier pour Violon, Alto et Violoncelle merci!!, la traversée du desert est longue. Mais elle vaut largement le coup. Ça fait du bien au moral et  c’est très reconfortant d’avoir ces premiers « oui »☺️" },
    ],
  },
  {
    nom: "Colas Zibaut",
    niche: "Spécialiste en Bien-être & Performance Numérique",
    portrait: "/immersion/communaute/colas-zibaut.jpg",
    titre: "j’ai mon premier client",
    surligne: ["Donc pour dire que la patience paie."],
    paragraphes: [
      "Collègues funneliens,",
      "Un petit mot pour vous partager que j’ai mon premier client. Quelle joie de voir enfin la section '“vente” se remplir sur system.io",
      "Bon, c’est un ami donc il avait forcément une confiance très forte, et j’ai mis plus de deux mois à le closer entre le premier et le second appel.",
      "Donc pour dire que la patience paie.",
      "Merci à l’équipe pour le soutien @Geoffrey Bonniot @Rémy Jupille @Maxime LEGROS 🙌🏻 Et merci à vous tous pour l’inspiration",
      "Pour celles et ceux qui ne sont pas encore à ce stade, j’espère que cette nouvelle vous donnera de la motivation 💪🏼",
    ],
    reponses: [
      { nom: "Lilian Céré", texte: "Bravo !!! 👏" },
      { nom: "Olivier CAETANO", texte: "Félicitations !" },
      { nom: "Barbara Bay", texte: "Bravo Colas !!!!! Et un grand merci à toi pour ce partage et pour tes encouragements. Je me réjouis de découvrir la suite de nos réussites aux uns et aux autres. Savoure bien cette première victoire, après ça sera tellement trop banal de closer 😂💗" },
      { nom: "Colas Zibaut", texte: "@Lilian Céré Merci !" },
      { nom: "Colas Zibaut", texte: "Thanks @Olivier CAETANO" },
      { nom: "Colas Zibaut", texte: "Merci @Barbara Bay, c’est sûr que ensuite, ça deviendra plus régulier (enfin j’espère), en attendant c’est sûr que c’est une source de réjouissance (et ça va me permettre d’éponger un peu mon budget pub au passage). Courage à toi !" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations @Colas Zibaut ! 🚀" },
      { nom: "Maxime LEGROS", texte: "Felicitations @Colas Zibaut 🚀🚀" },
    ],
  },
  {
    nom: "Patricia Nagant",
    niche: "Coach Thérapeutique et Holistique  -  \"Accoucheuse d'âme\"",
    portrait: "/immersion/communaute/patricia-nagant.jpg",
    titre: "je vis une aventure absolument magnifique",
    surligne: ["j’ai eu la joie de recevoir 11 appels"],
    paragraphes: [
      "Depuis le 25 juillet, jour où j’ai lancé mon tunnel de vente, je vis une aventure absolument magnifique et je suis remplie de gratitude ! En seulement quelques jours, j’ai eu la joie de recevoir 11 appels, et j’ai concrétisé 3 ventes en froid et 3 ventes en chaud, pour un total de 20400 €  ! 🙏✨",
      "Je suis tellement reconnaissante pour cette énergie qui circule, pour chaque personne qui a fait confiance à ce projet qui me tient tant à cœur, et pour tout ce que l’univers met en place pour soutenir « Être Aligné ». Je suis vraiment, vraiment fière de ce chemin parcouru, et j’ai hâte de voir tout ce qui continue à se déployer avec autant d’alignement et d’abondance !",
      "PS : Geoffrey, je pense que tu m’as oublié 😊 Peux-tu m’envoyer les deux vidéos promises suite à notre call ?",
      "@Geoffrey Bonniot @Rémy Jupille @Ludivine",
    ],
    reponses: [
      { nom: "Ludivine", texte: "Bravo @Patricia Nagant, ces résultats vous vous les devez à vous même ! Vous avez bien bossé 💪" },
      { nom: "Judith Nah", texte: "Waouuhhh Félicitations @Patricia Nagant De Beaux résultats !!💪🏻💪🏻" },
      { nom: "Rémy Jupille", texte: "Toutes mes félicitations, Patricia. Tu l'as grandement mérité !!" },
      { nom: "Patricia Nagant", texte: "@Judith Nah merci 🙏" },
      { nom: "Patricia Nagant", texte: "@Ludivine merci 🙏" },
      { nom: "Patricia Nagant", texte: "@Rémy Jupille merci 🙏" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations pour ces résultats ! Vous l’avez grandement mérité ! 🚀" },
      { nom: "Catherine Dumont", texte: "Magnifique Patricia 😀" },
      { nom: "Patricia Nagant", texte: "@Catherine Dumont merci 🙏" },
      { nom: "Patricia Nagant", texte: "@Geoffrey Bonniot merci 🙏" },
    ],
  },
  {
    nom: "Séverine Sassard",
    niche: "Coach perte de poids pour les femmes de plus de 40 ans",
    portrait: "/immersion/communaute/severine-sassard.jpg",
    titre: "j’ai réalisé mes 2 premières ventes en offre Bêta",
    surligne: ["C’est la première fois que j’arrive réellement à vendre"],
    paragraphes: [
      "Bonjour à toute l’équipe,",
      "Je voulais partager une petite (grande !) victoire : j’ai réalisé mes 2 premières ventes en offre Bêta 🎉",
      "Pour moi, c’est énorme. Je lutte beaucoup avec le syndrome de l’imposteur, alors réussir à concrétiser ces premières ventes a une valeur toute particulière.",
      "Un immense merci à toute l’équipe du Funnel Club. C’est la première fois que j’arrive réellement à vendre et je sais que votre accompagnement y est pour beaucoup.",
      "Pour celles et ceux que ça intéresse : – La communication s’est faite via mes réseaux sociaux – Les inscriptions sont passées par le webinar : une vente directement et une autre après le deuxième mail de relance.",
      "Maintenant, je reste dans le mouvement : accompagnement de mes clientes, alimentation de mon espace membre, animation de mes réseaux et préparation de mes publicités avec @Geoffrey Bonniot .",
      "Car après les premières ventes, une nouvelle question arrive : Est-ce que je vais réussir à en refaire, surtout avec un agenda de réservation vide ?",
      "Alors en ce moment, je travaille beaucoup mon mental. Je choisis de rester rationnelle : si je continue les actions, les résultats reviendront. C’est mathématique… Je refuse de laisser le doute prendre le dessus.",
      "Aujourd’hui, je suis fière et heureuse. J’ai hâte de me lancer dans l’aventure des publicités !",
      "Merci encore à vous tous",
    ],
    reponses: [
      { nom: "Clemence Privé", texte: "Top ! Bravo @Séverine SASSARD c’est un start qui est tjs encourageant. Comme tu dis faut savoir célébrer ses petites victoires !" },
      { nom: "Alexis Gaborit", texte: "Un grand bravo à toi @Séverine SASSARD" },
      { nom: "Séverine SASSARD", texte: "@Alexis Gaborit Merci beaucoup 🙏" },
      { nom: "Séverine SASSARD", texte: "@Clemence Privé Merci beaucoup🙏 c’est gentil !" },
      { nom: "Olivier CAETANO", texte: "Félicitations" },
      { nom: "Judith Nah", texte: "Waouh mes félicitations @Séverine SASSARD 💪🏻💪🏻💪🏻💪🏻 c est encourageant !" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations @Séverine SASSARD ! C’est mérité et ce n’est que le début ! 🚀" },
    ],
  },
  {
    nom: "Jeremy Renoux",
    niche: null,
    portrait: "/immersion/communaute/jeremy-renoux.jpg",
    titre: "mon premier close en 1X à 1800€",
    surligne: ["Il me parait loin le temps ou j’avais cette appréhension au téléphone"],
    paragraphes: [
      "Hello à toutes et tous ^^",
      "J’espère que vous allez bien et que vos tunnels se portent au mieux.",
      "Victoire qui fait du bien mon premier close en 1X à 1800€. Je suis plutôt content :D.  Alors petite dédicace à toi @Rémy Jupille et toi aussi @Geoffrey Bonniot . Il me parait loin le temps ou j’avais cette appréhension au téléphone avant d’appeler mes prospects….",
      "@Geoffrey Bonniot je t’ai fait une video en mp. Scaling or not scaling … that is the question ?",
      "Une excellente semaine à tous les funneliens et funneliennes",
      "Best",
      "Jerem",
    ],
    reponses: [
      { nom: "Ludivine", texte: "Yeahh, bravo @Jeremy Renoux ! Quelle belle évolution 🤩" },
      { nom: "Marjolaine Honor Luthier pour Violon, Alto et Violoncelle", texte: "J'ai hâte de ne plus avoir d'appréhension au téléphone en closing! Bravo pour tout ce chemin parcouru!!!! 🤩🎊" },
      { nom: "Jeremy Renoux", texte: "@Marjolaine Honor Luthier pour Violon, Alto et Violoncelle suis le process, les conseils de Rémy et de sa superbe équipe et ça marchera ^^.   Je te souhaite le meilleur des tunnels Marjolaine." },
      { nom: "Jeremy Renoux", texte: "@Ludivine cela me fait tellement plaisir venant de ta part. Tu te rappelles ces petits coups de fil… cela remonte maintenant… heureusement que tu étais là ;). Merci 😉 Passe une superbe journée" },
      { nom: "Geoffrey Bonniot", texte: "Félicitations @Jeremy Renoux ! C’est mérité ! 🚀" },
      { nom: "CHRISTIANE Rouault", texte: "Waouh c’est génial, bravo" },
      { nom: "Many Soliman", texte: "Bravooo jeremy😁😁🥳" },
    ],
  },
];
